const classical = [ 
"Anonymous|Carmina Burana|1100s|PLa1rC97wRkZg8wd3GnNYsVqhWJt3PzADO|Goliards|Carmina Burana",
"Hildegard of Bingen|Antiphons|1100s|PL830B1D04A2443A0A|Hildegard of Bingen|Antiphon",
"Guillaume de Machaut|Ballades|1300s|PLdOwnh1ORS3r8uGqgYwZ9VWO0zHgYccg2|Guillaume de Machaut|Ballade (forme fixe)",
"Francesco Landini|Ballatas and Songs|1300s|8aw7Wvivsv4|Francesco Landini|Ballata",
"Guillaume Dufay|Motets|1420-1447|PLWucXcpVWGbEpbIm4StOnCLiElfYG1Xz1|Guillaume Du Fay|Motet",
"Antoine Busnoys|Motets|1400s|owyMR2hAieE|Antoine Busnois|Motet",
"Johannes Ockeghem|Alma Redemptoris Mater|1400s|90uMGnTOUwc|Johannes Ockeghem|Alma Redemptoris Mater",
"John Browne|Stabat Mater|1490-1502|S4Mg4b18Yj0|John Browne (composer)|Stabat Mater",
"Josquin des Prez|Missa Pange lingua|1514|vlB1HR4BgUg|Josquin des Prez|Missa Pange lingua",
"John Taverner|The Western Wynde Mass|1530s|pJYFhEegS4w|John Taverner|Westron Wynde",
"Nicolas Gombert|Motets|1530-1550s|cxx7Stpx7bU|Nicolas Gombert|Motet",
"Cristóbal de Morales|Motets|1545-1547|lw6aq7oInvQ|Cristóbal de Morales|Motet",
"Antonio de Cabezón|Diferencias|1560s|XkYn6Ze-b3M|Antonio de Cabezón|",
"Thomas Tallis|Lamentations of Jeremiah|1565|rgRXLN6nlVU|Thomas Tallis|",
"Orlande de Lassus|Motets|1555-1604|TKE2EMnWT_g|Orlando di Lasso|Motet",
"Giovanni Pierluigi de Palestrina|Missa Papae Marcelli|1567|3n8XdKkrqgo|Giovanni Pierluigi da Palestrina|",
"Thomas Tallis|Spem in alium|1569|QmH1nZSGIyY|Thomas Tallis|Spem in alium",
"Tomás Luis de Victoria|O magnum mysterium|1572|9xPh-fXYAc4|Tomás Luis de Victoria|O magnum mysterium",
"Francisco Guerrero|Battle Mass|1582|jbK_2EwcuSQ|Francisco Guerrero (composer)|",
"Claudio Monteverdi|Madrigals|1587-1651|PLH2tnBZzETg6hf8rDAny1Zr0nCIh8_km0|Claudio Monteverdi|Madrigal",
"William Byrd|My Ladye Nevells Booke|1591|2PdRUGXAzoE|William Byrd|My Ladye Nevells Booke",
"William Byrd|Masses|1592-1595|PLa1rC97wRkZjqBBFTz94KhnoDFwet3zWb|William Byrd|Mass for Four Voices",
"Carlo Gesualdo|Madrigals|1594-1611|JEoOOYA31_E|Carlo Gesualdo|Madrigal",
"John Dowland|Lute Songs|1597-1612|PLI42ZRl64NuuxDIj8_9Va8djSY9NivVsy|John Dowland|Lute song",
"Giovanni Gabrieli|Sacrae symphoniae|1597-1615|OLAK5uy_kezqq4PrDf_1vfolmRJBXy3Ay_7g3WkCY|Giovanni Gabrieli|",
"John Wilbye|Madrigals|1598-1609|UoTQyxL8XM4|John Wilbye|Madrigal",
"Orlando Gibbons|Anthems|1600s|IUETZeGyMjo|Orlando Gibbons|Anthem",
"Jan Pieterszoon Sweelinck|Organ Works|1600-1621|RIIHDZs11dg|Jan Pieterszoon Sweelinck|",
"John Dowland|Lachrimae or Seaven Teares|1604|OLAK5uy_mksGm4beWKfRlNHxD469hvzLD4wO4afa8|John Dowland|Lachrimae, or Seaven Teares",
"Claudio Monteverdi|Orfeo|1607|jUep3sqe35o|Claudio Monteverdi|",
"Girolamo Frescobaldi|Keyboard Works|1608-1637|rQb_IHfMWko|Girolamo Frescobaldi|",
"Claudio Monteverdi|Vespers|1610|9rC-4AmUg8I|Claudio Monteverdi|Vespro della Beata Vergine",
"Thomas Weelkes|Anthems|1610s|XeQQyAg7rlw|Thomas Weelkes|Anthem",
"Thomas Campion|Books of Ayres|1613-1617|aZHVVzhMhiE|Thomas Campion|",
"Thomas Tomkins|Anthems|1620s|nCtNBD3XTgI|Thomas Tomkins|Anthem",
"Claudio Monteverdi|Combattimento|1624|xd13sePBlpU|Claudio Monteverdi|",
"John Jenkins|Fantasias|1630s|PL79264D4633487CF2|John Jenkins (composer)|Fantasia (music)",
"William Lawes|Consort Setts|1630s|0FDrO5kKdyc|William Lawes|",
"Heinrich Schütz|Musikalische Exequien|1636|-txG7o-ikt4|Heinrich Schütz|Musikalische Exequien",
"Gregorio Allegri|Miserere mei Deus|1640s|H3v9unphfi0|Gregorio Allegri|Miserere (Allegri)",
"Claudio Monteverdi|Il ritorno d’Ulisse in patria|1640|zunvtJBkS9E|Claudio Monteverdi|Il ritorno d'Ulisse in patria",
"Claudio Monteverdi|L’incoronazione di Poppea|1643|rzXEYAdPJ84|Claudio Monteverdi|L'incoronazione di Poppea",
"Giacomo Carissimi|Jephte|1650|_TN9VI1vNKM|Giacomo Carissimi|Jephte (Carissimi)",
"Barbara Strozzi|Cantatas|1650s|BWZoYpDLDX0|Barbara Strozzi|",
"Francesco Cavalli|La Calisto|1651|vZToJPUxEz4?start=56|Francesco Cavalli|La Calisto",
"Heinrich Schütz|The Christmas Story|1660|tFlR1-BMvq4|Heinrich Schütz|Christmas Story (Schütz)",
"Dietrich Buxtehude|Organ Music|1668-1707|PLH2tnBZzETg6bOPp2M3jJLlLzZJOLlX2-|Dieterich Buxtehude|",
"Heinrich Ignaz Franz Biber|Mystery Sonatas|1676|PLr0MsaDpKsY_Z8VqwgX4l8kkxQbBtwVXy|Heinrich Ignaz Franz Biber|Rosary Sonatas",
"Henry Purcell|Anthems|1676-1694|0jSRA2qKxAQ|Henry Purcell|Anthem",
"Henry Purcell|Chacony in G minor|1678|VvQQc4nkl2I|Henry Purcell|",
"Michel-Richard de Lalande|Grand Motets|1680-1700|0Dpnpw6J-cE|Michel Richard Delalande|Motet",
"Henry Purcell|Fantasias|1680|i5GBozzwWCI|Henry Purcell|",
"John Blow|Venus and Adonis|1683|0Uf0wfEMb-o|John Blow|",
"Henry Purcell|Dido and Aeneas|1683-1689|hb1_GaI-1yI|Henry Purcell|Dido and Aeneas",
"Jean-Baptiste Lully|Armide|1686|2zrbaEHomag|Jean-Baptiste Lully|Armide (Lully)",
"Alessandro Scarlatti|Cantatas|1688-1720|-ZDAmkt-2_k|Alessandro Scarlatti|",
"Juan de Araujo|Dixit Dominus|1689|gGZ9ykCZsfg|Juan de Araujo|",
"Marc-Antoine Charpentier|Te Deum|1690s|I3LIlzPtsmw|Marc-Antoine Charpentier|Te Deum (Charpentier)",
"Henry Purcell|The Fairy Queen|1692|QAvS3AypQfI|Henry Purcell|The Fairy-Queen",
"Henry Purcell|Come Ye Sons of Art, Away|1694|LSk_kA62duQ|Henry Purcell|Come Ye Sons of Art",
"Antonio Caldara|Maddalena ai piedi di Cristo|1698|tRdzPuHfKOY?start=24|Antonio Caldara|",
"Arcangelo Corelli|Twelve Concerti Grossi, Op. 6|1680s|PLKq64tL0GeMEk1d_wtyasghMWuBEXVcEg|Arcangelo Corelli|Twelve concerti grossi, Op. 6 (Corelli)",
"Antonio Vivaldi|Gloria, RV 589|1715|2eWjQOdYzMQ|Antonio Vivaldi|Gloria (Vivaldi)",
"Johann Sebastian Bach|Preludes, Fantasias, Toccatas & Fugues|1705-1748|YqpkLWATbbA|Johann Sebastian Bach|",
"Jean-Philippe Rameau|Pièces de clavecin|1706-1747|gkcUOht1i4c|Jean-Philippe Rameau|",
"Georg Philipp Telemann|Trumpet Concerto in D major|1708-1714|lMsncAgvIXo|Georg Philipp Telemann|",
"Antonio Vivaldi|Concerto for Two Trumpets|1711|SVtLeR2K8sk|Antonio Vivaldi|",
"Antonio Vivaldi|L’estro armonico|1711|xn4KUN3yfMg|Antonio Vivaldi|",
"Antonio Vivaldi|Stabat Mater|1712|r9O80oxwhp8|Antonio Vivaldi|Stabat Mater",
"François Couperin|Twenty-seven Ordres|1713-1730|bNj8bgnmErc|François Couperin|",
"Johann Sebastian Bach|Orgelbüchlein|1708-1717|vGz-QhGgB_4?start=138|Johann Sebastian Bach|Orgelbüchlein",
"Antonio Vivaldi|Juditha triumphans|1716|dd_2D9Rg_Tk|Antonio Vivaldi|Juditha triumphans",
"George Frideric Handel|Water Music|1717|EVAB2z1RPu4|George Frideric Handel|",
"Marin Marais|Pièces de viole, quatrième livre|1717|1pTLTGIwZ2w|Marin Marais|",
"Johann Sebastian Bach|Violin Concertos|1717-1723|OLAK5uy_mapCK75PdhcYRGrJFapYuZNy-42yjONKA|Johann Sebastian Bach|Violin Concerto in A minor (Bach)",
"Johann Sebastian Bach|Concerto for Two Violins|1730|ILKJcsET-NM?start=7|Johann Sebastian Bach|Concerto for Two Violins (Bach)",
"Johann Sebastian Bach|Orchestral Suites|1717-1742|eNh3ppZVrSI|Johann Sebastian Bach|Orchestral suites (Bach)",
"Johann Sebastian Bach|Six Suites for Solo Cello|1717-1723|OLAK5uy_nGCSv7-JrYyqrVHo_gR-6vCMyaGCgsxbU|Johann Sebastian Bach|Cello Suites (Bach)",
"Johann Sebastian Bach|Sonatas & Partitas for Solo Violin|1720|PLUKf5X9_kU5OXpP3roQbW0YiYbZ9Ybf4H|Johann Sebastian Bach|Sonatas and Partitas for Solo Violin (Bach)",
"George Frideric Handel|Keyboard Suites|1720-1733|HrXOVNzTeKo|George Frideric Handel|",
"Johann Sebastian Bach|Brandenburg Concertos|1721|PLecKPCyj4yRPXmmt0yFK3pF2HY8kux3RH|Johann Sebastian Bach|Brandenburg Concertos",
"Johann Sebastian Bach|Magnificat|1723|EsUWG2axB3w|Johann Sebastian Bach|",
"Johann Sebastian Bach|Great Cantatas|1723-1729|ODjl6A3v6b0|Johann Sebastian Bach|Bach cantata",
"Johann Sebastian Bach|St. John Passion|1724|zMf9XDQBAaI|Johann Sebastian Bach|St John Passion",
"George Frideric Handel|Giulio Cesare|1724|ppAUohisvG8|George Frideric Handel|Giulio Cesare",
"Johann Sebastian Bach|Six English Suites|1725|OLAK5uy_kK2CSscuXYjmQ45FK5KXmwXZHmthMdOhY|Johann Sebastian Bach|English Suites (Bach)",
"George Frideric Handel|Rodelinda|1725|VNY61LRMp4U|George Frideric Handel|",
"Antonio Vivaldi|The Four Seasons|1725|4rgSzQwe5DQ|Antonio Vivaldi|The Four Seasons (Vivaldi)",
"Johann Sebastian Bach|Six Violin Sonatas|1725|s7wmR0EqEGQ|Johann Sebastian Bach|",
"Johann Sebastian Bach|Keyboard Partitas|1726-1731|XiG8AGn5Qz8|Johann Sebastian Bach|",
"Johann Sebastian Bach|Motets|1726-1735|jdtYTR6zP8A|Johann Sebastian Bach|List of motets by Johann Sebastian Bach",
"Johann Sebastian Bach|St. Matthew Passion|1727|ZwVW1ttVhuQ|Johann Sebastian Bach|St Matthew Passion",
"George Frideric Handel|Coronation Anthems|1727|OLAK5uy_nzUPah-9VRU8z9TJ9oKBtipzhJ9UYqEys|George Frideric Handel|https://en.wikipedia.org/wiki/Coronation_anthem#Handel.27s_coronation_anthems",
"John Gay|The Beggar’s Opera|1728|Lq7g_NRKHU0|John Gay|The Beggar's Opera",
"Johann Sebastian Bach|French Suites|1730|0sDleZkIK-w|Johann Sebastian Bach|French Suites (Bach)",
"Georg Philipp Telemann|Paris Quartets|1730|mBCoDRX4a0Q|Georg Philipp Telemann|Paris quartets",
"Georg Philipp Telemann|Tafelmusik|1733|xNFkKhfdgZM|Georg Philipp Telemann|Tafelmusik (Telemann)",
"Johann Sebastian Bach|Christmas Oratorio|1734-1735|98UjjwzJBFE|Johann Sebastian Bach|Christmas Oratorio",
"George Frideric Handel|Ariodante|1735|JGnW-HZCiD8|George Frideric Handel|",
"George Frideric Handel|Organ Concertos|1735-1751|PLawrJgP30lZzVcDwDX9Q-6shONTUEzQcT|George Frideric Handel|Organ concertos, Op. 4 (Handel)",
"Jean-Philippe Rameau|Les Indes galantes|1735|_aPKLslVDSE|Jean-Philippe Rameau|Les Indes galantes",
"Giovanni Battista Pergolesi|Stabat Mater|1736|OLAK5uy_nlZhmKoJSxliIWRwq3lF7jO2aumS6-eU4|Giovanni Battista Pergolesi|Stabat Mater (Pergolesi)",
"Jean-Philippe Rameau|Castor et Pollux|1737-1754|i-xWnhex11E|Jean-Philippe Rameau|Castor et Pollux",
"George Frideric Handel|Serse|1738|WH7GSJoDUDM|George Frideric Handel|Serse",
"Johann Sebastian Bach|Harpsichord Concertos|1739|wC_kuLSnuXk|Johann Sebastian Bach|",
"George Frideric Handel|Concerti grossi, Op. 6|1739|Y8tE9MYOCeI|George Frideric Handel|Concerti grossi, Op. 6 (Handel)",
"Johann Sebastian Bach|The Well-Tempered Clavier|1740-1742|PL3U0S8lpDeK7dqgWS6aoSMe-TaeczQnuI|Johann Sebastian Bach|The Well-Tempered Clavier",
"Domenico Scarlatti|Keyboard Sonatas|1740s|4yBQlZ06G40|Domenico Scarlatti|",
"Johann Sebastian Bach|Goldberg Variations|1741|OLAK5uy_lzcXH_zLclgfHiWX40qbP5mCoZe3H-Q6Q|Johann Sebastian Bach|Goldberg Variations",
"George Frideric Handel|Messiah|1742|IUZEtVbJT5c?start=12|George Frideric Handel|Messiah (Handel)",
"Carl Philipp Emanuel Bach|Keyboard Sonatas|1742-1744|B1vzh4lledU|Carl Philipp Emanuel Bach|",
"Johann Sebastian Bach|The Musical Offering|1747|yhMAq2PhRaQ|Johann Sebastian Bach|The Musical Offering",
"George Frideric Handel|Judas Maccabaeus|1747|dzuR-6S8pt8|George Frideric Handel|Judas Maccabaeus (Handel)",
"Johann Sebastian Bach|Mass in B minor|1749|3FLbiDrn8IE|Johann Sebastian Bach|",
"George Frideric Handel|Music for the Royal Fireworks|1749|fNqJ8mED1VE|George Frideric Handel|Music for the Royal Fireworks",
"Johann Sebastian Bach|The Art of Fugue|1750|N6sUlZa-IrU?start=8|Johann Sebastian Bach|The Art of Fugue",
"George Frideric Handel|Theodora|1750|OLAK5uy_nuM-86t8kAFY6xE4DSRxzCY8KxKiCicY4|George Frideric Handel|Theodora (Handel)",
"William Boyce|Eight Symphonies, Op. 2|1760|ONv2X10nUw0|William Boyce (composer)|",
"Joseph Haydn|Symphonies nos. 6-8|1761|58tDranbYg4|Joseph Haydn|",
"Christoph Willibald Gluck|Orfeo ed Euridice|1762|JUpZ1Npj23M|Christoph Willibald Gluck|Orfeo ed Euridice",
"Leopold Mozart|Trumpet Concerto|1762|vWMRRfNnErI|Leopold Mozart|Trumpet Concerto (Leopold Mozart)",
"Joseph Haydn|Cello Concertos|1762-1783|zLhC4tLeT8k|Joseph Haydn|Cello Concerto No. 1 (Haydn)",
"Wolfgang Amadeus Mozart|Violin Sonatas|1763-1788|PLxXjllvtBC_pbcA0TQjVNTqpm2-sTEit2|Wolfgang Amadeus Mozart|Violin Sonatas, KV 6–9 (Mozart)",
"Giuseppe Tartini|Devil’s Trill Sonata|1765|ZkX8YyA4Wp4?start=4|Giuseppe Tartini|Violin Sonata in G minor (Tartini)",
"Christoph Willibald Gluck|Alceste|1767|iDFnGqG7qt8|Christoph Willibald Gluck|Alceste (Gluck)",
"Andre-Ernest-Modeste Grétry|Zémire et Azor|1771|GiQq7VRQBp8|André Grétry|Zémire et Azor",
"Joseph Haydn|Keyboard Sonatas|1771-1795|9KTgA1i06xU|Joseph Haydn|",
"Luigi Boccherini|String Quintets|1772-1803|OLAK5uy_kiyjaPh8cuZKFTnCNtcKKQs2yLBpYoxxQ|Luigi Boccherini|String Quintet in E major, Op. 11, No. 5 (Boccherini)",
"Joseph Haydn|Symphony No. 45, \"Farewell\"|1772|OpD9ofCm6Ak|Joseph Haydn|Symphony No. 45 (Haydn)",
"Wolfgang Amadeus Mozart|String Quintets|1773-1791|PLFpllkY6JbXzppCDMRmodtZ0GFPtQnUQG|Wolfgang Amadeus Mozart|String Quintet No. 1 (Mozart)",
"Wolfgang Amadeus Mozart|Piano Sonatas|1775-1789|PLEhQ5Ooc2lLqc6wq7sgzTHOour-kPcUju|Wolfgang Amadeus Mozart|Sonata in C major for piano four-hands, K. 521",
"Wolfgang Amadeus Mozart|Violin Concerto No. 5, \"Turkish\"|1775|5f3gO2GWIew|Wolfgang Amadeus Mozart|Violin Concerto No. 5 (Mozart)",
"Wolfgang Amadeus Mozart|Piano Concerto No. 9, \"Jeunehomme\"|1777|plfty7jbM_g|Wolfgang Amadeus Mozart|Piano Concerto No. 9 (Mozart)",
"Christoph Willibald Gluck|Iphigénie en Tauride|1779|ROzh7i_RSyc|Christoph Willibald Gluck|Iphigénie en Tauride",
"Wolfgang Amadeus Mozart|Sinfonia concertante in E flat major|1780|_0hTDZ0whpU|Wolfgang Amadeus Mozart|Sinfonia Concertante for Violin, Viola and Orchestra (Mozart)",
"Wolfgang Amadeus Mozart|Idomeneo|1781|rg4nYs7lPeU|Wolfgang Amadeus Mozart|Idomeneo",
"Wolfgang Amadeus Mozart|Haydn Quartets|1782-1785|PLEhQ5Ooc2lLq3KKbtGC69mmLJyyYeoKcS|Wolfgang Amadeus Mozart|Haydn Quartets (Mozart)",
"Wolfgang Amadeus Mozart|Die Entführung aus dem Serail|1782|iYOTeHL14uQ|Wolfgang Amadeus Mozart|Die Entführung aus dem Serail",
"Wolfgang Amadeus Mozart|Serenade No. 10, \"Gran partita\"|1783|k0ig72-rj0s|Wolfgang Amadeus Mozart|Serenade No. 10 (Mozart)",
"Wolfgang Amadeus Mozart|Great Mass in C minor|1783|Ez0kqVShFEs?start=4|Wolfgang Amadeus Mozart|Great Mass in C minor, K. 427",
"Wolfgang Amadeus Mozart|Symphony No. 36, \"Linz\"|1783|Im4B8CKkdoo|Wolfgang Amadeus Mozart|Symphony No. 36 (Mozart)",
"Joseph Haydn|Symphony No. 83, \"La poule\"|1785|6rD32fnEvyA?start=3|Joseph Haydn|Symphony No. 83 (Haydn)",
"Wolfgang Amadeus Mozart|Piano Concerto No. 20|1785|devtF2EoZDs|Wolfgang Amadeus Mozart|Piano Concerto No. 20 (Mozart)",
"Wolfgang Amadeus Mozart|Piano Concerto No. 21|1785|df-eLzao63I|Wolfgang Amadeus Mozart|Piano Concerto No. 21 (Mozart)",
"Wolfgang Amadeus Mozart|Piano Concerto No. 22|1785|P9eEbEfEqoU?start=25|Wolfgang Amadeus Mozart|Piano Concerto No. 22 (Mozart)",
"Wolfgang Amadeus Mozart|Horn Concerto No. 4|1786|gtOkOYTM_5E?start=35|Wolfgang Amadeus Mozart|Horn Concerto No. 4 (Mozart)",
"Wolfgang Amadeus Mozart|Piano Concerto No. 23|1786|TmrDa_ddon8|Wolfgang Amadeus Mozart|Piano Concerto No. 23 (Mozart)",
"Wolfgang Amadeus Mozart|The Marriage of Figaro|1786|55ik-PzAXsQ|Wolfgang Amadeus Mozart|The Marriage of Figaro",
"Wolfgang Amadeus Mozart|Piano Concerto No. 24|1786|POWVTXuB68I|Wolfgang Amadeus Mozart|Piano Concerto No. 24 (Mozart)",
"Wolfgang Amadeus Mozart|Piano Quartet in E flat major|1786|8KdkGctFHq8|Wolfgang Amadeus Mozart|Piano Quartet No. 2 (Mozart)",
"Wolfgang Amadeus Mozart|Piano Concerto No. 25|1786|WIjAGbyQO9M|Wolfgang Amadeus Mozart|Piano Concerto No. 25 (Mozart)",
"Wolfgang Amadeus Mozart|Symphony No. 38, \"Prague\"|1786|1t18CpBuJJM?start=3|Wolfgang Amadeus Mozart|Symphony No. 38 (Mozart)",
"Joseph Haydn|The Seven Last Words of Christ|1787|R2ljYXsWWGs?start=30|Joseph Haydn|The Seven Last Words of Christ (Haydn)",
"Wolfgang Amadeus Mozart|Eine kleine Nachtmusik|1787|156u4nV2uGE?start=4|Wolfgang Amadeus Mozart|Eine kleine Nachtmusik",
"Wolfgang Amadeus Mozart|Don Giovanni|1787|aL2VdxseTvE|Wolfgang Amadeus Mozart|Don Giovanni",
"Wolfgang Amadeus Mozart|Coronation Concerto|1788|RcBcMbOHzhI|Wolfgang Amadeus Mozart|Piano Concerto No. 26 (Mozart)",
"Wolfgang Amadeus Mozart|Symphony No. 39|1788|fAiF1PNlQ50?start=12|Wolfgang Amadeus Mozart|Symphony No. 39 (Mozart)",
"Wolfgang Amadeus Mozart|Symphony No. 40|1788|QyQ-POuTNn8?start=4|Wolfgang Amadeus Mozart|Symphony No. 40 (Mozart)",
"Wolfgang Amadeus Mozart|Symphony No. 41, \"Jupiter\"|1788|yZpFrydm6G4?start=14|Wolfgang Amadeus Mozart|Symphony No. 41 (Mozart)",
"Wolfgang Amadeus Mozart|Prussian String Quartets|1789-1790|p_62BnrkIcs|Wolfgang Amadeus Mozart|Prussian Quartets (Mozart)",
"Wolfgang Amadeus Mozart|Clarinet Quintet|1789|xTNbclgU3h4|Wolfgang Amadeus Mozart|Clarinet Quintet (Mozart)",
"Joseph Haydn|String Quartets, Op. 64|1790|PLwEx-3EdmA0YaWxqVt19sYYNSDaRL7MLe|Joseph Haydn|String Quartets, Op. 64 (Haydn)",
"Wolfgang Amadeus Mozart|Così fan tutte|1790|MXCEuYL1pBU|Wolfgang Amadeus Mozart|Così fan tutte",
"Wolfgang Amadeus Mozart|Ave verum corpus|1791|gDKCK_6WLTg|Wolfgang Amadeus Mozart|Ave verum corpus (Mozart)",
"Wolfgang Amadeus Mozart|The Magic Flute|1791|cE64eIZi9Lw|Wolfgang Amadeus Mozart|The Magic Flute",
"Joseph Haydn|Symphony No. 94, \"Surprise\"|1791|tF5kr251BRs|Joseph Haydn|",
"Wolfgang Amadeus Mozart|La clemenza di Tito|1791|c0-1RWLrz4o|Wolfgang Amadeus Mozart|La clemenza di Tito",
"Wolfgang Amadeus Mozart|Piano Concerto No. 27|1791|Yaaksm19IzU|Wolfgang Amadeus Mozart|Piano Concerto No. 27 (Mozart)",
"Wolfgang Amadeus Mozart|Clarinet Concerto|1791|YT_63UntRJE|Wolfgang Amadeus Mozart|Clarinet Concerto (Mozart)",
"Wolfgang Amadeus Mozart|Requiem|1791|Dp2SJN4UiE4?start=76|Wolfgang Amadeus Mozart|Requiem (Mozart)",
"Domenico Cimarosa|Il matrimonio segreto|1792|f4R0CQeumC8|Domenico Cimarosa|Il matrimonio segreto",
"Joseph Haydn|Symphony No. 104, \"London\"|1794|OitPLIowJ70|Joseph Haydn|Symphony No. 104 (Haydn)",
"Joseph Haydn|Trumpet Concerto|1795|ZUZYoVw7moc|Joseph Haydn|Trumpet Concerto (Haydn)",
"Luigi Cherubini|Médée|1796|fW-gtPnslo8|Luigi Cherubini|Médée (Cherubini)",
"Joseph Haydn|Trumpet Concerto|1797|ZUZYoVw7moc|Joseph Haydn|Trumpet Concerto (Haydn)",
"Joseph Haydn|String Quartets, Op. 76|1797|PLFpllkY6JbXyfY5NrlOjfUzRI_un853Uc|Joseph Haydn|String Quartets, Op. 76 (Haydn)",
"Ludwig van Beethoven|Sonata Pathetique|1798|XuldgIR02dY|Ludwig van Beethoven|Piano Sonata No. 8 (Beethoven)",
"Joseph Haydn|Nelson Mass|1798|MeSzYLdpWac|Joseph Haydn|Nelson Mass",
"Joseph Haydn|The Creation|1798|EuIs7R2BpvQ|Joseph Haydn|The Creation (Haydn)",
"John Field|Piano Concertos|1799-1832|PL1IXBSY4jc2vKY8mAadc__tWnPjaaRGDV|John Field (composer)|Piano Concerto No. 2 (Field)",
"Joseph Haydn|String Quartets, Op. 77|1799|J9G4foIL6zw|Joseph Haydn|",
"Ludwig van Beethoven|String Quartets, Op. 18|1800|de-NLJ0doao|Ludwig van Beethoven|String Quartets, Op. 18 (Beethoven)",
"Ludwig van Beethoven|Symphony No. 1|1800|EVKdd-gI_aQ|Ludwig van Beethoven|Symphony No. 1 (Beethoven)",
"Ludwig van Beethoven|Spring Sonata|1800|C35Rjyo4W0o|Ludwig van Beethoven|Violin Sonata No. 5 (Beethoven)",
"Ludwig van Beethoven|Moonlight Sonata|1801|-VmQNKaOeEw?start=4|Ludwig van Beethoven|Piano Sonata No. 14 (Beethoven)",
"Joseph Haydn|The Seasons|1801|l3O2K-LyJ9o|Joseph Haydn|The Seasons (Haydn)",
"Ludwig van Beethoven|Symphony No. 2|1802|bEiYmeeV6sI|Ludwig van Beethoven|Symphony No. 2 (Beethoven)",
"Ludwig van Beethoven|Piano Concerto No. 3|1803|AjMBtkTMLYU?start=46|Ludwig van Beethoven|Piano Concerto No. 3 (Beethoven)",
"Ludwig van Beethoven|Symphony No. 3, \"Eroica\"|1803|fhHcty9OM-0?start=19|Ludwig van Beethoven|Symphony No. 3 (Beethoven)",
"Ludwig van Beethoven|Kreutzer Sonata|1803|OF9fneQ50Us?start=13|Ludwig van Beethoven|Violin Sonata No. 9 (Beethoven)",
"Johann Nepomuk Hummel|Trumpet Concerto|1803|902St2UAmfA|Johann Nepomuk Hummel|Trumpet Concerto (Hummel)",
"Ludwig van Beethoven|Appassionata|1805|E5JObP74jcw|Ludwig van Beethoven|Piano Sonata No. 23 (Beethoven)",
"Ludwig van Beethoven|Triple Concerto|1805|pkXGtE8_cig?start=50|Ludwig van Beethoven|Triple Concerto (Beethoven)",
"Ludwig van Beethoven|Piano Concerto No. 4 in G major|1806|6lvBQJjxw4c|Ludwig van Beethoven|Piano Concerto No. 4 (Beethoven)",
"Ludwig van Beethoven|String Quartets, Op. 59, \"Razumovsky\"|1806|oXLKu-HglnM|Ludwig van Beethoven|String Quartets, Op. 59 (Beethoven)",
"Ludwig van Beethoven|Symphony No. 4|1806|Ec6i45d74nk|Ludwig van Beethoven|Symphony No. 4 (Beethoven)",
"Ludwig van Beethoven|Violin Concerto|1806|0Cg_0jepxow|Ludwig van Beethoven|Violin Concerto (Beethoven)",
"Ludwig van Beethoven|Symphony No. 5|1807|fuPrcnpIRx8?start=17|Ludwig van Beethoven|Symphony No. 5 (Beethoven)",
"Ludwig van Beethoven|Piano Trio in D major, Op. 70, No. 1, \"Ghost\"|1808|_XgK71JuBXA?start=3|Ludwig van Beethoven|Piano Trios, Op. 70 (Beethoven)",
"Ludwig van Beethoven|Symphony No. 6, \"Pastoral\"|1808|nXgBtAD5daM|Ludwig van Beethoven|Symphony No. 6 (Beethoven)",
"Ludwig van Beethoven|Piano Concerto No. 5 in E flat major|1809|3TiYGxOQDYw|Ludwig van Beethoven|Piano Concerto No. 5 (Beethoven)",
"Fernando Sor|Guitar Works|1810-1830s|I2wTJAcRWg4|Fernando Sor|",
"Ludwig van Beethoven|Les Adieux|1810|6c9B3K4ii-c|Ludwig van Beethoven|Piano Sonata No. 26 (Beethoven)",
"Ludwig van Beethoven|Piano Trio in B flat major, Op. 97, \"Archduke\"|1811|ezRNLXBbB8Q|Ludwig van Beethoven|Piano Trio, Op. 97 (Beethoven)",
"Carl Maria von Weber|Clarinet Concertos nos. 1 & 2|1811|37kaymgFkUI?start=9|Carl Maria von Weber|",
"Ludwig van Beethoven|Symphony No. 7|1812|-4788Tmz9Zo|Ludwig van Beethoven|Symphony No. 7 (Beethoven)",
"Ludwig van Beethoven|Symphony No. 8|1812|WcgxxciDdy0?start=3|Ludwig van Beethoven|Symphony No. 8 (Beethoven)",
"Carl Lowe|Ballads|1812-1862|-U6xOEKyjSI|Carl Loewe|",
"Gioachino Rossini|Tancredi|1813|aIhjHLw5ZCY|Gioachino Rossini|Tancredi",
"Gioachino Rossini|L’italiana in Algeri|1813|b9YmR5zFyLE|Gioachino Rossini|L'italiana in Algeri",
"Louis Spohr|Nonet in F major|1813|StIxuL01mj0|Louis Spohr|",
"Ludwig van Beethoven|Fidelio|1814|sm7hGCSkhTE|Ludwig van Beethoven|Fidelio",
"Franz Schubert|Lieder|1814-1828|fYiw37hpZtY|Franz Schubert|",
"Ludwig van Beethoven|Cello Sonatas, Op. 102|1815|nUFGQqzznkM|Ludwig van Beethoven|Cello Sonatas Nos. 4 and 5 (Beethoven)",
"Nicolò Paganini|Violin Concertos nos. 1-6|1815-1830|OLAK5uy_kd-Lb1LH0hUtj_i75jeuu0phvBktV-3dg|Niccolò Paganini|Violin Concerto No. 1 (Paganini)",
"Gioachino Rossini|The Barber of Seville|1816|OloXRhesab0|Gioachino Rossini|The Barber of Seville",
"Franz Schubert|Symphony No. 5|1816|OHkot1TmvZU?start=15|Franz Schubert|Symphony No. 5 (Schubert)",
"Nicolò Paganini|24 Caprices for Solo Violin|1817|PL1X3qTzT40VmKDpW_PGodU62pyC8ZKjxy|Niccolò Paganini|24 Caprices for Solo Violin (Paganini)",
"Franz Schubert|Violin Sonata in A major|1817|to1IAyAv0iI|Franz Schubert|",
"Gioachino Rossini|La cenerentola|1817|SeVezYX1m6M|Gioachino Rossini|La Cenerentola",
"Ludwig van Beethoven|Hammerklavier|1818|ETjfAIHpJjY|Ludwig van Beethoven|Piano Sonata No. 29 (Beethoven)",
"Franz Schubert|Trout Quintet|1819|XdaDdsreaE0?start=7|Franz Schubert|Trout Quintet",
"Frederic Chopin|Mazurkas|1820-1847|OLAK5uy_lhjI44up4wwjnXZQsLUb0pUHXR3LRpJsk|Frédéric Chopin|Mazurkas (Chopin)",
"Ludwig van Beethoven|Piano Sonata No. 30|1820|luiOoylLTvc?start=7|Ludwig van Beethoven|Piano Sonata No. 30 (Beethoven)",
"Carl Maria von Weber|Der Freischütz|1821|ZdMqHNcL6xI|Carl Maria von Weber|Der Freischütz",
"Ludwig van Beethoven|Piano Sonata in A flat major, Op. 110|1821|-WxCQlu2l2I|Ludwig van Beethoven|Piano Sonata No. 31 (Beethoven)",
"Ludwig van Beethoven|Piano Sonata No. 32|1822|8AQ9hZTpgwM?start=24|Ludwig van Beethoven|Piano Sonata No. 32 (Beethoven)",
"Franz Schubert|Symphony No. 8, \"Unfinished\"|1822|3tisvEpblig?start=30|Franz Schubert|Symphony No. 8 (Schubert)",
"Franz Schubert|Wanderer Fantasy|1822|-sEdFF9Bldw?start=12|Franz Schubert|Wanderer Fantasy",
"Franz Schubert|Die schöne Müllerin|1823|_YeITW9A8Rk|Franz Schubert|Die schöne Müllerin",
"Ludwig van Beethoven|Missa solemnis|1823|hnrFUFVcDmc?start=3|Ludwig van Beethoven|Missa solemnis (Beethoven)",
"Ludwig van Beethoven|Diabelli Variations|1823|hTmQU4jEgJw|Ludwig van Beethoven|Diabelli Variations",
"Juan Crisóstomo de Arriaga|String Quartets|1824|OLAK5uy_mlEYiNKOSyuhQ5s93iPrH5liQKfcIlFZ0|Juan Crisóstomo Arriaga|",
"Ludwig van Beethoven|Symphony No. 9, \"Choral\"|1824|rOjHhS5MtvA?start=107|Ludwig van Beethoven|Symphony No. 9 (Beethoven)",
"Franz Schubert|Octet in F major, D. 803|1824|fnpVu8Eihj4|Franz Schubert|Octet (Schubert)",
"Franz Schubert|Death and the Maiden|1824|otdayisyIiM|Franz Schubert|String Quartet No. 14 (Schubert)",
"Franz Schubert|Arpeggione Sonata|1824|NNcQuY1isEI|Franz Schubert|Arpeggione Sonata",
"Ludwig van Beethoven|Late String Quartets|1825-1826|PLO6zBTEo45QhwK0K1NWmIDesKrduHficv|Ludwig van Beethoven|Late string quartets (Beethoven)",
"Felix Mendelssohn|Octet|1825|Vw1kcQ-QbZw|Felix Mendelssohn|Octet (Mendelssohn)",
"Felix Mendelssohn|Songs Without Words|1825-1845|nFOPeI2gPaM|Felix Mendelssohn|Songs Without Words",
"Franz Schubert|Piano Sonata in D major, D. 850|1825|gguHcUWUVOE|Franz Schubert|Piano Sonata in D major, D 850 (Schubert)",
"Gioachino Rossini|Il viaggio a Reims|1825|VKQCAIs7ClA|Gioachino Rossini|Il viaggio a Reims",
"Franz Schubert|String Quartet in G major, D. 887|1826|iaL-kLYxDIw|Franz Schubert|String Quartet No. 15 (Schubert)",
"Felix Mendelssohn|A Midsummer Night’s Dream|1826|SEkcP8lZvZA|Felix Mendelssohn|A Midsummer Night's Dream (Mendelssohn)",
"Franz Schubert|Piano Sonata in G major, D. 894|1826|cBisjKwg43U|Franz Schubert|Piano Sonata in G major, D 894 (Schubert)",
"Franz Schubert|Piano Trio in B flat major|1827|qWFrKxxTwag|Franz Schubert|Piano Trio No. 1 (Schubert)",
"Franz Schubert|Impromptus|1827|24DugWBRkYg|Franz Schubert|Impromptus (Schubert)",
"Franz Schubert|Winterreise|1827|tnuvs2w7ges?start=4|Franz Schubert|Winterreise",
"Franz Schubert|Piano Trio in E flat major, D. 929|1827|yFyv7c1XyYU|Franz Schubert|Piano Trio No. 2 (Schubert)",
"Franz Schubert|Fantasy in C, D. 934|1827|NV1kANo4qPI|Franz Schubert|Fantasy for violin and piano (Schubert)",
"Franz Schubert|Fantasia in F minor|1828|UyjzqPPXDcw|Franz Schubert|Fantasia in F minor (Schubert)",
"Franz Schubert|Symphony No. 9, \"The Great\"|1828|TPpvJnwf5BU|Franz Schubert|Symphony No. 9 (Schubert)",
"Franz Schubert|String Quartet in C major|1828|Dc3iX7x73JY|Franz Schubert|String Quartet No. 14 (Schubert)",
"Franz Schubert|Schwanengesang|1828|_fZCNfonuzQ|Franz Schubert|Schwanengesang",
"Franz Schubert|Piano Sonata in C minor, D. 958|1828|ltvKcZ9U5QA|Franz Schubert|Schubert's last sonatas",
"Franz Schubert|Piano Sonata in A major, D. 959|1828|olmgg0y2o9A|Franz Schubert|Schubert's last sonatas",
"Franz Schubert|Piano Sonata in B flat major, D. 960|1828|oCn0PjPHdrc|Franz Schubert|Schubert's last sonatas",
"Frederic Chopin|Nocturnes|1829-1847|OLAK5uy_ltKS5aE5Jx9f3bK8g6rrBvn6tbRZJnPX0|Frédéric Chopin|Nocturnes (Chopin)",
"Frédéric Chopin|Piano Concertos|1829-1830|2bFo65szAP0|Frédéric Chopin|Piano Concerto No. 1 (Chopin)",
"Frédéric Chopin|Waltzes|1829-1847|PLjWMBsFxAe08Iy6FKXOr8P9LnSNt09TP8|Frédéric Chopin|Waltzes (Chopin)",
"Felix Mendelssohn|String Quartets nos. 1 & 2|1827-1829|r0F6tN6IMiI|Felix Mendelssohn|String Quartet No. 1 (Mendelssohn)",
"Gioachino Rossini|Guillaume Tell|1829|S5Pk9CCkkvk|Gioachino Rossini|William Tell (opera)",
"Hector Berlioz|Symphonie fantastique|1830|5HgqPpjIH5c|Hector Berlioz|Symphonie fantastique",
"Gaetano Donizetti|Anna Bolena|1830|CXyN1qY2RTw|Gaetano Donizetti|Anna Bolena",
"Felix Mendelssohn|The Hebrides|1830|Ed1pmhHXFwY?start=3|Felix Mendelssohn|The Hebrides (overture)",
"Frederic Chopin|Études|1830-1837|PLyTrgbHEyUqQ6CmKNZCKjbZC9GwK-UCt2|Frédéric Chopin|Études (Chopin)",
"Vincenzo Bellini|La sonnambula|1831|pouHB3wImTc|Vincenzo Bellini|La sonnambula",
"Felix Mendelssohn|Piano Concerto No. 1|1831|2GGx8TRWFVA|Felix Mendelssohn|Piano Concerto No. 1 (Mendelssohn)",
"Vincenzo Bellini|Norma|1831|GN75XDDm_DI|Vincenzo Bellini|Norma (opera)",
"Gaetano Donizetti|L’elisir d’amore|1832|zx1Y5ljpmzk?start=110|Gaetano Donizetti|L'elisir d'amore",
"Gioachino Rossini|Stabat Mater|1832-1841|8CB_49aqxps|Gioachino Rossini|Stabat Mater (Rossini)",
"Felix Mendelssohn|Symphony No. 4, \"Italian\"|1833|_HX_jF1_Tgc?start=3|Felix Mendelssohn|Symphony No. 4 (Mendelssohn)",
"Hector Berlioz|Harold in Italy|1834|Q4NC4E5RXik?start=3|Hector Berlioz|",
"Gaetano Donizetti|Lucia di Lammermoor|1835|_maNJkybAwI|Gaetano Donizetti|",
"Vincenzo Bellini|I puritani|1835|3CKto2oZ2w8|Vincenzo Bellini|I puritani",
"Robert Schumann|Études symphoniques|1835-1852|PLC0324E2JQQZNlEmh1aEBeHAzimfisoxL|Robert Schumann|Symphonic Studies",
"Robert Schumann|Carnaval|1835|zk8v0HkzKzc|Robert Schumann|Carnaval (Schumann)",
"Robert Schumann|Piano Sonata No. 1|1835|KM_4iZGBcWM|Robert Schumann|Piano Sonata No. 1 (Schumann)",
"Frederic Chopin|Ballades|1835-1841|qb0Ebqe9JJo|Frédéric Chopin|Ballades (Chopin)",
"Giacomo Meyerbeer|Les Huguenots|1836|sK0xbDR3ckU|Giacomo Meyerbeer|Les Huguenots",
"Felix Mendelssohn|String Quartets, Op. 44|1837-1838|YYnZnPlOywk|Felix Mendelssohn|String Quartet No. 3 (Mendelssohn)",
"Robert Schumann|Davidsbündlertänze|1837|xXwMvwlZ2j8|Robert Schumann|Davidsbündlertänze",
"Hector Berlioz|Grande messe des morts|1837|HofoFYxqIgU|Hector Berlioz|Requiem (Berlioz)",
"Franz Liszt|Années de pèlerinage|1837-1877|LuiwjTiGHdE|Franz Liszt|Années de pèlerinage",
"Robert Schumann|Kinderszenen|1838|yibf6QNjgGU|Robert Schumann|Kinderszenen",
"Robert Schumann|Kreisleriana|1838|J5FayGAxTf0?start=23|Robert Schumann|Kreisleriana",
"Robert Schumann|Fantasie in C|1839|ZRZjHKX-JMA|Robert Schumann|Fantasie in C (Schumann)",
"Hector Berlioz|Roméo et Juliette|1839|VZhBexI6F6U|Hector Berlioz|Roméo et Juliette (Berlioz)",
"Frederic Chopin|Preludes|1839|QWFR9joxbpc?start=4|Frédéric Chopin|Preludes (Chopin)",
"Felix Mendelssohn|Piano Trios nos. 1 & 2|1839-1845|-PAFzEnJ6NU?start=7|Felix Mendelssohn|Piano Trio No. 1 (Mendelssohn)",
"Frederic Chopin|Piano Sonata No. 2|1839|KUQX-eAOWw0?start=7|Frédéric Chopin|Piano Sonata No. 2 (Chopin)",
"Franz Liszt|Paraphrases & Transcriptions|1840|Y8MGa0MOt3c|Franz Liszt|",
"Robert Schumann|Dichterliebe|1840|bZvsTlk85Xg|Robert Schumann|Dichterliebe",
"Robert Schumann|Frauenliebe und -leben|1840|eVkJOs8vdRM|Robert Schumann|",
"Robert Schumann|Liederkreis, Op. 24|1840|3DCiOA2vpnQ|Robert Schumann|Liederkreis, Op. 24 (Schumann)",
"Robert Schumann|Liederkreis, Op. 39|1840|X0pFd-UQ99c|Robert Schumann|Liederkreis, Op. 39 (Schumann)",
"Felix Mendelssohn|Variations sérieuses|1841|4EYw7pLbRI8|Felix Mendelssohn|Variations sérieuses",
"Robert Schumann|Symphony No. 1, \"Spring\"|1841|1Lk2V6YOcIc?start=4|Robert Schumann|Symphony No. 1 (Schumann)",
"Richard Wagner|Der fliegende Holländer|1841-1860|Z8dtRIFVmDw|Richard Wagner|Der fliegende Holländer",
"Robert Schumann|Piano Quartet|1842|sM9iSRm97Ws|Robert Schumann|Piano Quartet (Schumann)",
"Franz Berwald|Symphonies|1842-1845|PL4D14bmfCxVU3eRigboIrmwqiMTM_yAQB|Franz Berwald|",
"Felix Mendelssohn|Symphony No. 3, \"Scottish\"|1842|rw6slNXSzNg?start=3|Felix Mendelssohn|Symphony No. 3 (Mendelssohn)",
"Robert Schumann|String Quartets|1842|PLxXjllvtBC_qFkTJtWb2yJzOvxj8vsqFC|Robert Schumann|",
"Giuseppe Verdi|Nabucco|1842|XttF0vg0MGo|Giuseppe Verdi|",
"Robert Schumann|Piano Quintet|1842|rHsvD6_gRyo|Robert Schumann|Piano Quintet (Schumann)",
"Mikhail Glinka|Ruslan and Lyudmila|1842|QW3IwWFkpfc|Mikhail Glinka|Ruslan and Lyudmila (opera)",
"Gaetano Donizetti|Don Pasquale|1843|_RZ-pOOgbL4|Gaetano Donizetti|Don Pasquale",
"Felix Mendelssohn|Violin Concerto in E minor|1844|I03Hs6dwj7E|Felix Mendelssohn|Violin Concerto (Mendelssohn)",
"Hector Berlioz|Le carnaval romain|1844|j_3YoeLz7Rc?start=3|Hector Berlioz|https://en.wikipedia.org/wiki/Overtures_by_Hector_Berlioz#Le_carnaval_romain",
"Frederic Chopin|Piano Sonata No. 3|1844|s9Ofz4TjfhM|Frédéric Chopin|Piano Sonata No. 3 (Chopin)",
"Robert Schumann|Piano Concerto|1845|3jbHbDena_U?start=27|Robert Schumann|Piano Concerto (Schumann)",
"Richard Wagner|Tannhäuser|1845-1861|XdqRLSWXDlM?start=3|Richard Wagner|Tannhäuser (opera)",
"Felix Mendelssohn|Elijah|1846|pduEw6cn5N0?start=114|Felix Mendelssohn|Elijah (oratorio)",
"Robert Schumann|Symphony No. 2|1846|z1PQrwsZdPc|Robert Schumann|Symphony No. 2 (Schumann)",
"Robert Schumann|Piano Trios|1847-1851|dzF3C-GZkSo?start=98s|Robert Schumann|Piano Trio No. 1 (Schumann)",
"Giuseppe Verdi|Macbeth|1947-1865|MI8V78mPsMA|Giuseppe Verdi|Macbeth (opera)",
"Charles-Valentin Alkan|Grande sonate \"Les quatres âges\"|1848|EUUgoJqVSFY|Charles-Valentin Alkan|",
"Johann Strauss the Elder|Radetzky March|1848|eab_eFtTKFs|Johann Strauss I|Radetzky March",
"Franz Liszt|Hungarian Rhapsodies|1848-1885|OLAK5uy_lUPAFJF39Ltb_VMYFXxa5CEvIBFGQ4Bok|Franz Liszt|Hungarian Rhapsodies",
"Richard Wagner|Lohengrin|1848|zyodILZEQFg|Richard Wagner|",
"Robert Schumann|Concertstück for Four Horns|1849|mpfJ2ghmAsI|Robert Schumann|Konzertstück for Four Horns and Orchestra",
"Robert Schumann|Fantasiestück, Op. 73|1849|28kD_f1UZdU|Robert Schumann|Fantasiestücke, Op. 73",
"Otto Nicolai|The Merry Wives of Windsor|1849|S0oHhdJ__ME|Otto Nicolai|The Merry Wives of Windsor (opera)",
"Robert Schumann|Symphony No. 3, \"Rhenish\"|1850|3lRdCGIp-rg?start=3|Robert Schumann|Symphony No. 3 (Brahms)",
"Robert Schumann|Cello Concerto in A minor|1850|NayPFVXYo9o|Robert Schumann|Cello Concerto (Schumann)",
"Franz Liszt|Transcendental Études|1851|PLEQ0hp9avWWF2uZCkzh0M4RSmDN7FiTTZ|Franz Liszt|Transcendental Études",
"Giuseppe Verdi|Rigoletto|1851|fYDI6MWkCW8|Giuseppe Verdi|Rigoletto",
"Robert Schumann|Symphony No. 4|1851|Fq98d0JOiKQ?start=3|Robert Schumann|Symphony No. 2 (Schumann)",
"Johannes Brahms|Lieder|1851-1896|QQ45pJwyO9o|Johannes Brahms|",
"Giuseppe Verdi|Il trovatore|1853|JRRkhpJr0pA|Giuseppe Verdi|",
"Giuseppe Verdi|La traviata|1853|pu7zWrIMV_g|Giuseppe Verdi|La traviata",
"Franz Liszt|Piano Sonata in B minor|1853|IeKMMDxrsBE|Franz Liszt|Piano Sonata in B minor (Liszt)",
"Robert Schumann|Scenes from Goethe's Faust|1853|fYU1z3LJIL4|Robert Schumann|Scenes from Goethe's Faust",
"Hector Berlioz|La damnation de Faust|1854|Ws_YvHfG1yQ|Hector Berlioz|La damnation de Faust",
"Franz Liszt|Les préludes|1854|jb2bkVQwtBs|Franz Liszt|Les préludes",
"Johannes Brahms|Piano Trio No. 1|1854-1891|EK7sZfccL04|Johannes Brahms|Piano Trio No. 1 (Brahms)",
"Franz Liszt|Piano Concertonz Liszt|Piano Concertos Nos. 1 & 2|vMbSpGhnhuE|rz1xuCZ0sBM|Franz Liszt|Piano Concerto No. 1 (Liszt)",
"Hector Berlioz|Les nuits d’été|1856|3HrRrTl88FM?start=3|Hector Berlioz|Les nuits d'été",
"Cesar Franck|Six Pièces, opp. 16-21|1856-1864|Kjh-H88gemQ|César Franck|",
"Giuseppe Verdi|Simon Boccanegra|1857-1881|h2eM5ByJhj8|Giuseppe Verdi|",
"Jacques Offenbach|Orpheus in the Underworld|1858-1874|vEnW5_GTooI|Jacques Offenbach|Orpheus in the Underworld",
"Richard Wagner|Wesendonck Lieder|1858|HFxB6DoEUXs|Richard Wagner|Wesendonck Lieder",
"Hector Berlioz|Les troyens|1858|JVuj-b0zXVE|Hector Berlioz|Les Troyens",
"Johannes Brahms|Piano Concerto No. 1|1859|1jB_6fpYY3o?start=60|Johannes Brahms|Piano Concerto No. 1 (Brahms)",
"Charles Gounod|Faust|1859|Q7oVDMVXyqw|Charles Gounod|Faust (opera)",
"Giuseppe Verdi|Un ballo in maschera|1859|bjPSlFcuVNE|Giuseppe Verdi|Un ballo in maschera",
"Richard Wagner|Tristan und Isolde|1859|J-qoaioG2UA|Richard Wagner|Tristan und Isolde",
"Johannes Brahms|String Sextets nos. 1 & 2|1860-1865|mTz3Z4RrI6Y|Johannes Brahms|String Sextet No. 1 (Brahms)",
"Pyotr Ilyich Tchaikovsky|Songs|1860-1893|Gk9NGtX6aGU|Pyotr Ilyich Tchaikovsky|None but the Lonely Heart (Tchaikovsky)",
"Johannes Brahms|Piano Quartets nos. 1 & 3|1861-1874|7BifP-9elgE|Johannes Brahms|Piano Quartet No. 1 (Brahms)",
"Edvard Grieg|Songs|1861-1905|PLO9FsKeaaDxUg1JP1Robvn-qUKWn6ZLgb|Edvard Grieg|",
"Gabriel Faure|Mélodies|1861-1921|RRcfSNmm0c8|Gabriel Fauré|Trois mélodies, Op. 7 (Fauré)",
"Franz Liszt|Faust Symphony|1861|3ZUQ7yZTFco|Franz Liszt|Faust Symphony",
"Henri Vieuxtemps|Violin Concerto No. 5|1861|oCFKcQsXeZ4|Henri Vieuxtemps|Violin Concerto No. 5 (Vieuxtemps)",
"Giuseppe Verdi|La forza del destino|1862-1869|drbHCt0lwzo|Giuseppe Verdi|La forza del destino",
"Henryk Wieniawski|Violin Concerto No. 2|1862|T7KNd6W5OXo|Henryk Wieniawski|",
"Johannes Brahms|Piano Quintet|1862-1864|Ewuwa-gujBg|Johannes Brahms|Piano Quintet (Brahms)",
"Camille Saint-Saens|Introduction and Rondo capriccioso|1863|v5r1-1PqKrg|Camille Saint-Saëns|Introduction and Rondo Capriccioso",
"Gioachino Rossini|Petite messe solennelle|1863-1867|CqrzmdevQSI|Gioachino Rossini|Petite messe solennelle",
"Georges Bizet|The Pearl Fishers|1863|csgt5pktsto|Georges Bizet|Les pêcheurs de perles",
"Anton Bruckner|Masses nos. 1-3|1864-1868|D3s561KCnt8|Anton Bruckner|",
"Jacques Offenbach|La belle Hélène|1864|lEuv4vMJjUo|Jacques Offenbach|La belle Hélène",
"Edvard Grieg|Lyric Pieces|1864-1901|OLAK5uy_lp9dMQQpyS2g_ap546Fiupuxs1Fya-USw|Edvard Grieg|Lyric Pieces",
"Johannes Brahms|Cello Sonatas nos. 1 & 2|1865-1886|6oyLJHpe8Z8|Johannes Brahms|Cello Sonata No. 1 (Brahms)",
"Bedrich Smetana|The Bartered Bride|1866-1870|QLUm_yvnyo4|Bedřich Smetana|The Bartered Bride",
"Richard Wagner|Die Meistersinger von Nürnberg|1867|fDIkzHjHRhI?start=3|Richard Wagner|Die Meistersinger von Nürnberg",
"Johann Strauss II|The Blue Danube|1867|IDaJ7rFg66A|Johann Strauss II|The Blue Danube",
"Modest Mussorgsky|Night on Bald Mountain|1867|52iOdAVU4C8?start=4|Modest Mussorgsky|Night on Bald Mountain",
"Giuseppe Verdi|Don Carlos|1867-1886|wIQGijoUB1Y|Giuseppe Verdi|Don Carlos",
"Johannes Brahms|A German Requiem|1868|ZXU9vqVdudM?start=3|Johannes Brahms|A German Requiem (Brahms)",
"Max Bruch|Violin Concerto No. 1|1868|KDJ6Wbzgy3E?start=3|Max Bruch|Violin Concerto No. 1 (Bruch)",
"Camille Saint-Saens|Piano Concerto No. 2|1868|tVCvJZtzkqQ|Camille Saint-Saëns|",
"Edvard Grieg|Piano Concerto|1868|I1Yoyz6_Los|Edvard Grieg|Piano Concerto (Grieg)",
"Henri Duparc|Mélodies|1868-1884|CKoeBLh2Y2M|Henri Duparc (composer)|Mélodie",
"Arrigo Boito|Mefistofele|1868-1876|OLAK5uy_mO5AcL1kMfvMZF0rXDnMelmPZ6FYBH7yk|Arrigo Boito|Mefistofele",
"Ambroise Thomas|Hamlet|1868|P70KBHeDw7U|Ambroise Thomas|Hamlet (Thomas)",
"Modest Mussorgsky|Boris Godunov|1869-1908|16NiqpBZMpM|Modest Mussorgsky|Boris Godunov (opera)",
"Johannes Brahms|Hungarian Dances|1869-1880|PLr8wuhKLeLgwsyJNeX8d2LMTIUsZ5XlEN|Johannes Brahms|Hungarian Dances (Brahms)",
"Mily Alekseyevich Balakirev|Islamey|1869-1902|78AslTXMp30|Mily Balakirev|",
"Pyotr Ilyich Tchaikovsky|Romeo and Juliet|1869-1880|f6qZUCi7ToQ?start=4|Pyotr Ilyich Tchaikovsky|Romeo and Juliet (Tchaikovsky)",
"Leo Delibes|Coppélia|1870|haxnvx6SHIo|Léo Delibes|Coppélia",
"Richard Wagner|Siegfried Idyll|1870|wolO4fJr70Y?start=3|Richard Wagner|Siegfried Idyll",
"Giuseppe Verdi|Aida|1871|b8rsOzPzYr8|Giuseppe Verdi|Aida",
"Pyotr Ilyich Tchaikovsky|String Quartet No. 1|1871|1w7w6J5ODqc|Pyotr Ilyich Tchaikovsky|String Quartet No. 1 (Tchaikovsky)",
"Camille Saint-Saens|Cello Concerto No. 1|1872|pfBkzWNQTpI?start=3|Camille Saint-Saëns|",
"Anton Bruckner|Symphony No. 3|1873-1889|kY4l2Xx3crs?start=3|Anton Bruckner|Symphony No. 3 (Bruckner)",
"Johannes Brahms|String Quartets|1873-1875|nWLe7ed8my0|Johannes Brahms|String Quartets, Op. 51 (Brahms)",
"Edouard Lalo|Symphonie espagnole|1874|4JgJqD38hL4?start=3|Édouard Lalo|Symphonie espagnole",
"Georges Bizet|Carmen|1874|EseMHr6VEM0?start=127|Georges Bizet|Carmen",
"Johann Strauss II|Die Fledermaus|1874|PLKq64tL0GeMF3BWvlZH_rL02bR3HQDoE7|Johann Strauss II|Die Fledermaus",
"Giuseppe Verdi|Requiem|1874|Nlq9lJRElBk?start=3|Giuseppe Verdi|Requiem (Verdi)",
"Anton Bruckner|Symphony No. 4, \"Romantic\"|1874-1888|o0g82i784bw?start=68|Anton Bruckner|Symphony No. 4 (Bruckner)",
"Modest Mussorgsky|Pictures at an Exhibition|1874-1922|kkC3chi_ysw|Modest Mussorgsky|Pictures at an Exhibition",
"Richard Wagner|Der Ring des Nibelungen|1874|1PBhlPeTJ_g?start=713|Richard Wagner|Der Ring des Nibelungen",
"Hugo Wolf|Lieder|1875-1897|d1uAcRPNSto|Hugo Wolf|",
"Edvard Grieg|Peer Gynt|1875|7kpqALC8IbI|Edvard Grieg|Peer Gynt (Grieg)",
"Pyotr Ilyich Tchaikovsky|Piano Concerto No. 1|1875|hNfpMRSCFPE?start=4|Pyotr Ilyich Tchaikovsky|Piano Concerto No. 1 (Tchaikovsky)",
"Anton Bruckner|Symphony No. 5|1875-1878|iOTzCgMxy_o|Anton Bruckner|Symphony No. 5 (Bruckner)",
"Gabriel Faure|Nocturnes|1875-1921|sqw5B9B9j4M|Gabriel Fauré|",
"Johannes Brahms|Symphony No. 1|1876|FXGQ0Y45yQk|Johannes Brahms|Symphony No. 1 (Brahms)",
"Alexander Borodin|Symphony No. 2|1876|FmUsL6biVro|Alexander Borodin|Symphony No. 2 (Borodin)",
"Gabriel Faure|Violin Sonata No. 1|1876|xIQwc-RxK8I|Gabriel Fauré|Violin Sonata No. 1 (Fauré)",
"Amilcare Ponchielli|La Gioconda|1876|EKxFcD8cFPI?start=27|Amilcare Ponchielli|La Gioconda (opera)",
"Bedrich Smetana|String Quartet No. 1, \"From My Life\"|1876|ZWW0dXCpTuA|Bedřich Smetana|String Quartet No. 1 (Smetana)",
"Pyotr Ilyich Tchaikovsky|Variations on a Rococo Theme|1876|_591VkMY4iQ|Pyotr Ilyich Tchaikovsky|Variations on a Rococo Theme",
"Pyotr Ilyich Tchaikovsky|The Seasons|1876|OLAK5uy_mEkjXexzva_ItaG6Cr4IxjJAGHvUvi-ZQ|Pyotr Ilyich Tchaikovsky|The Seasons (Tchaikovsky)",
"Pyotr Ilyich Tchaikovsky|Swan Lake|1876|9rJoB7y6Ncs?start=3486|Pyotr Ilyich Tchaikovsky|Swan Lake",
"Johannes Brahms|Symphony No. 2|1877|qbcfuMlNRWg?start=15|Johannes Brahms|Symphony No. 2 (Brahms)",
"Camille Saint-Saens|Samson and Delilah|1877|X67Cguz5J0s?start=5|Camille Saint-Saëns|Samson and Delilah (opera)",
"Johannes Brahms|Violin Concerto|1878|UFl9xuYP5T8?start=34|Johannes Brahms|Violin Concerto (Brahms)",
"Pablo de Sarasate|Zigeunerweisen|1878|ufIlOXXMqs0|Pablo de Sarasate|",
"Antonin Dvorak|Slavonic Dances|1878-1886|OLAK5uy_m_arCKH99i_HPp0jdr89cbTntDgs_8av4|Antonín Dvořák|Slavonic Dances",
"Arthur Sullivan|H.M.S. Pinafore|1878|OLAK5uy_kY5lK7VsByK7LN4YqEUcqpbAbiXz8sfcY|Arthur Sullivan|H.M.S. Pinafore",
"Pyotr Ilyich Tchaikovsky|Eugene Onegin|1878|8n_j3cC_Is8|Pyotr Ilyich Tchaikovsky|Eugene Onegin (opera)",
"Pyotr Ilyich Tchaikovsky|Symphony No. 4|1878|YnRkXtsD_54|Pyotr Ilyich Tchaikovsky|Symphony No. 4 (Tchaikovsky)",
"Pyotr Ilyich Tchaikovksy|Violin Concerto|1878|cbJZeNlrYKg|Pyotr Ilyich Tchaikovsky|Violin Concerto (Tchaikovsky)",
"Johannes Brahms|Violin Sonatas|1879-1888|9T6vnY2x-Jc|Johannes Brahms|Violin Sonata No. 1 (Brahms)",
"Bedrich Smetana|Má vlast|1879|PLiN-7mukU_RGqaKhCWnR4Pj_Ft_coB7ZX|Bedřich Smetana|Má vlast",
"Gabriel Faure|Piano Quartets 1 & 2|1879|NUzlJpKoQy0|Gabriel Fauré|",
"Modest Mussorgsky|Khovanshchina|1880|13E-RJF-FaA|Modest Mussorgsky|Khovanshchina",
"Gabriel Faure|Élégie|1880|m84iLSh56KU|Gabriel Fauré|Élégie (Fauré)",
"Hans Rott|Symphony in E major|1880|fTwYSQOhsKc|Hans Rott|",
"Jacques Offenbach|The Tales of Hoffmann|1880|g7czptgEvvU|Jacques Offenbach|The Tales of Hoffmann",
"Pyotr Ilyich Tchaikovsky|Serenade for Strings|1880|M2ZU-1EyVOw?start=4|Pyotr Ilyich Tchaikovsky|Serenade for Strings (Tchaikovsky)",
"Camille Saint-Saens|Violin Concerto No. 3|1880|DZxwiABbock|Camille Saint-Saëns|Violin Concerto No. 3 (Saint-Saëns)",
"Bedrich Smetana|From the Homeland|1880|f-0qjmN9yzg|Bedřich Smetana|",
"Pyotr Ilyich Tchaikovsky|1812 Overture|1880|QUpuAvQQrC0|Pyotr Ilyich Tchaikovsky|1812 Overture",
"Charles-Marie Widor|Symphony for Organ No. 5|1880|glWX6sQQ_dQ?start=115|Charles-Marie Widor|Symphony for Organ No. 5",
"Alexander Borodin|String Quartet No. 2|1881|9YVd5efkUnw?start=749|Alexander Borodin|String Quartet No. 2 (Borodin)",
"Johannes Brahms|Piano Concerto No. 2|1881|BszBccYHuAk|Johannes Brahms|Piano Concerto No. 2 (Brahms)",
"Richard Wagner|Parsifal|1881|JsqPWZNEQvY|Richard Wagner|Parsifal",
"Anton Bruckner|Symphony No. 6|1881|OflReU5RlZM?start=12|Anton Bruckner|Symphony No. 6 (Bruckner)",
"Pyotr Ilyich Tchaikovsky|Piano Trio in A minor|1882|Frnnhv1TVzU|Pyotr Ilyich Tchaikovsky|Piano Trio (Tchaikovsky)",
"Pablo de Sarasate|Concert Fantasy on Carmen|1883|pNGoAUz0nhE|Pablo de Sarasate|",
"Johannes Brahms|Symphony No. 3|1883|u68ETRjNQME?start=3|Johannes Brahms|Symphony No. 3 (Brahms)",
"Emmanuel Chabrier|España|1883|9iHFZX9xD3M?start=3|Emmanuel Chabrier|España (Chabrier)",
"Anton Bruckner|Symphony No. 7|1883|uaV3eEJB55c?start=3|Anton Bruckner|Symphony No. 7 (Bruckner)",
"Leo Delibes|Lakmé|1883|C1ZL5AxmK_A|Léo Delibes|Lakmé",
"Jules Massenet|Manon|1884|6czlA02iI_U|Jules Massenet|Manon",
"Cesar Franck|Prélude, choral et fugue|1884|-Dr2CK4R0l4|César Franck|Prélude, Choral et Fugue (Franck)",
"Johannes Brahms|Symphony No. 4|1885|7QLuYj2jxoc|Johannes Brahms|Symphony No. 4 (Brahms)",
"Antonin Dvorak|Symphony No. 7|1885|YwD7JcpRe0w?start=3|Antonín Dvořák|Symphony No. 7 (Dvořák)",
"Cesar Franck|Symphonic Variations|1885|_XrWnggqboM|César Franck|Symphonic Variations (Franck)",
"Gustav Mahler|Lieder eines fahrenden Gesellen|1885|RxmGLjumt7Q|Gustav Mahler|Lieder eines fahrenden Gesellen",
"Johann Strauss II|Der Zigeunerbaron|1885|caGQy0Dipbk?start=13|Johann Strauss II|",
"Pyotr Ilyich Tchaikovsky|Manfred Symphony|1885|S6Mn1UjggBY?start=3|Pyotr Ilyich Tchaikovsky|Manfred Symphony",
"Richard Strauss|Lieder|1885-1933|bmoP0_lLAQ8|Richard Strauss|https://en.wikipedia.org/wiki/Richard_Strauss#Lieder",
"Arthur Sullivan|The Mikado|1885|PL9yl-ZQyD9w9ko2-qOteHjAB3WCL6fNsf|Arthur Sullivan|The Mikado",
"Cesar Franck|Violin Sonata in A major|1886|oKi8YmP9Ki4|César Franck|Violin Sonata (Franck)",
"Camille Saint-Saens|Carnival of the Animals|1886|k2RPKMJmSp0|Camille Saint-Saëns|The Carnival of the Animals",
"Camille Saint-Saens|Symphony No. 3, \"Organ\"|1886|ZWCZq33BrOo|Camille Saint-Saëns|Symphony No. 3 (Saint-Saëns)",
"John Stainer|The Crucifixion|1887|_tshvog2Eow?start=81|John Stainer|The Crucifixion (Stainer)",
"Reynaldo Hahn|Mélodies|1887-1947|PL4p5S2PvyPNwEaOSMuD4jqnRadG87xlrT|Reynaldo Hahn|Mélodie",
"Alexander Borodin|Prince Igor|1887|CzmIu-VjRCM?start=60|Alexander Borodin|Prince Igor",
"Nicolai Rimsky-Korsakov|Capriccio espagnol|1887|Lh6mDL-VwYw|Nikolai Rimsky-Korsakov|",
"Jules Massenet|Werther|1887|p90HEtK1Bi0|Jules Massenet|Werther",
"Johannes Brahms|Double Concerto|1887|GMurNzAAcLA|Johannes Brahms|Double Concerto (Brahms)",
"Anton Bruckner|Symphony No. 8|1887-1892|elVHvTrEM34|Anton Bruckner|Symphony No. 8 (Bruckner)",
"Richard Strauss|Violin Sonata|1887|d73FVIKbl5k|Richard Strauss|Violin Sonata (Strauss)",
"Giuseppe Verdi|Otello|1887|Sm_Usoo7LvY|Giuseppe Verdi|Otello",
"Cesar Franck|Symphony in D minor|1888|uRWFjK11lfw?start=3|César Franck|Symphony in D minor (Franck)",
"Gustav Mahler|Symphony No. 1|1888|ISBfOpztUZM|Gustav Mahler|Symphony No. 1 (Mahler)",
"Nicolai Rimsky-Korsakov|Scheherazade|1888|zY4w4_W30aQ|Nikolai Rimsky-Korsakov|Scheherazade (Rimsky-Korsakov)",
"Hugo Wolf|Mörike Lieder|1888|F4D9DEgFo6k|Hugo Wolf|",
"Pyotr Ilyich Tchaikovsky|Symphony No. 5|1888|JUk0WZVCnk4|Pyotr Ilyich Tchaikovsky|Symphony No. 5 (Tchaikovsky)",
"Nicolai Rimsky-Korsakov|Russian Easter Festival Overture|1888|hbDYtAHTQoE?start=10|Nikolai Rimsky-Korsakov|Russian Easter Festival Overture",
"Erik Satie|Gymnopédies & Gnossiennes|1888-1897|OLAK5uy_m3aQCZ456zkiyxQFekp-itO0hqWokyy_c|Erik Satie|",
"Alexander Scriabin|Preludes|1888-1914|ry5L3_0XVuk|Alexander Scriabin|24 Preludes, Op. 11 (Scriabin)",
"Antonin Dvorak|Symphony No. 8|1889|QXAv-NGppFw?start=3|Antonín Dvořák|Symphony No. 8 (Dvořák)",
"Hugo Wolf|Goethe Lieder|1889|c8eALT6ULpc|Hugo Wolf|",
"Pyotr Ilyich Tchaikovsky|The Sleeping Beauty|1889|EDFlRq5RnbQ?start=55|Pyotr Ilyich Tchaikovsky|The Sleeping Beauty (ballet)",
"Richard Strauss|Don Juan|1889|XG4uBRBMdzY?start=3|Richard Strauss|Don Juan (Strauss)",
"Richard Strauss|Tod und Verklärung|1889|mu2M67IQ68Q|Richard Strauss|Death and Transfiguration",
"Ernest Chausson|Poème de l’amour et de la mer|1890|0TfHB9USgBI|Ernest Chausson|Poème de l'amour et de la mer",
"Hugo Wolf|Spanisches Liederbuch|1890|OLAK5uy_mRoCWCP5vDJHITmtRxWGc_omxLEkQqr-c|Hugo Wolf|Spanisches Liederbuch (Wolf)",
"Gabriel Faure|Requiem|1890-1893|UnilUPXmipM|Gabriel Fauré|Requiem (Fauré)",
"Pietro Mascagni|Cavalleria rusticana|1890|7OvsVSWB4TI|Pietro Mascagni|Cavalleria rusticana",
"Pyotr Ilyich Tchaikovsky|The Queen of Spades|1890|aA3lTy7OMM8|Pyotr Ilyich Tchaikovsky|The Queen of Spades (opera)",
"Claude Debussy|Fêtes galantes|1891-1904|nQaWW2flSAQ|Claude Debussy|Fêtes galantes (Debussy)",
"Jean Sibelius|Songs|1891-1917|OLAK5uy_nMnV74EgwdCzmLQf8JLrinuEwgAkNSR_M|Jean Sibelius|",
"Johannes Brahms|Clarinet Quintet|1891|NijYtozUHaw|Johannes Brahms|Clarinet Quintet (Brahms)",
"Ruggero Leoncavallo|Pagliacci|1892|G1XkhDU8Y9E|Ruggero Leoncavallo|Pagliacci",
"Alexander Scriabin|Piano Sonatas|1892-1913|krapei3Fjcc|Alexander Scriabin|Piano Sonata No. 3 (Scriabin)",
"Jean Sibelius|En saga|1892-1902|SMlxb5rWLEY|Jean Sibelius|En saga",
"Sergei Rachmaninoff|Twenty-Four Preludes|1892-1910|eKzZ2x_KPxc|Sergei Rachmaninoff|",
"Pyotr Ilyich Tchaikovsky|The Nutcracker|1892|CtRLa92bINc?start=4983|Pyotr Ilyich Tchaikovsky|The Nutcracker",
"Johannes Brahms|Klavierstücke, opp. 116-19|1892-1893|-doSRJepT1s|Johannes Brahms|",
"Jean Sibelius|Kullervo|1892|hDzor0VXy0M|Jean Sibelius|Kullervo (Sibelius)",
"Claude Debussy|String Quartet|1893|5VMQuHMq8QQ|Claude Debussy|String Quartet (Debussy)",
"Engelburt Humperdinck|Hänsel und Gretel|1893|JnMEI4aoUfo|Engelbert Humperdinck (composer)|",
"Erik Satie|Vexations|1893|7OjuC2XZm6s|Erik Satie|Vexations",
"Antonin Dvorak|American Quartet|1893|HrqgMrwG4i0|Antonín Dvořák|String Quartet No. 12 (Dvořák)",
"Giacomo Puccini|Manon Lescaut|1893|IOxpbOb9hwk|Giacomo Puccini|Manon Lescaut (Puccini)",
"Pyotr Ilyich Tchaikovksy|Symphony No. 6, \"Pathétique\"|1893|KvGC8hZC29U|Pyotr Ilyich Tchaikovsky|Symphony No. 6 (Tchaikovsky)",
"Giuseppe Verdi|Falstaff|1893|We0heyFkqXU|Giuseppe Verdi|Falstaff (opera)",
"Jean Sibelius|Karelia Suite|1893|adKwG9ZuzFw|Jean Sibelius|Karelia Suite",
"Antonin Dvorak|Symphony No. 9|1893|jOofzffyDSA?start=20|Antonín Dvořák|Symphony No. 9 (Dvořák)",
"Anton Stepanovich Arensky|Piano Trio No. 1|1894|fvOiW5eLzL4|Anton Arensky|Piano Trio No. 1 (Arensky)",
"Claude Debussy|Prélude à L’après-midi d’un faune|1894|Y9iDOt2WbjY?start=3|Claude Debussy|Prélude à l'après-midi d'un faune",
"Gustav Mahler|Symphony No. 2, \"Resurrection\"|1894|sHsFIv8VA7w|Gustav Mahler|Symphony No. 2 (Mahler)",
"Johannes Brahms|Clarinet Sonatas|1894|V39p4Fbgz_A|Johannes Brahms|Clarinet Sonatas (Brahms)",
"Richard Strauss|Till Eulenspiegels lustige Streiche|1895|vXFYfr1K_NU|Richard Strauss|Till Eulenspiegel's Merry Pranks",
"Antonin Dvorak|Cello Concerto in B minor|1895|190faUQ7xJg|Antonín Dvořák|Cello Concerto (Dvořák)",
"Serge Rachmaninoff|Symphony No. 1|1895|Zr-ifrS5Qq4|Sergei Rachmaninoff|Symphony No. 1 (Rachmaninoff)",
"Gustave Charpentier|Louise|1896|vsaEh8QtBq4|Gustave Charpentier|Louise (opera)",
"Umberto Giordano|Andrea Chénier|1896|QuO1iioMDnw|Umberto Giordano|Andrea Chénier",
"Anton Bruckner|Symphony No. 9|1896|swULVZ5zLkM|Anton Bruckner|Symphony No. 9 (Bruckner)",
"Ernest Chausson|Poème|1896|5fRUy4ELg-E|Ernest Chausson|Poème (Chausson)",
"Jean Sibelius|Lemminkäinen Suite|1896-1939|pvVgU61cIbs|Jean Sibelius|",
"Giacomo Puccini|La bohème|1896|H_1OtRt0_ho|Giacomo Puccini|La bohème",
"Gustav Mahler|Symphony No. 3|1896|oSBfEPAnDsY?start=3|Gustav Mahler|Symphony No. 3 (Mahler)",
"Camille Saint-Saens|Piano Concerto No. 5, \"Egyptian\"|1896|OVZcDkJ3-bQ|Camille Saint-Saëns|Piano Concerto No. 5 (Saint-Saëns)",
"Richard Strauss|Also sprach Zarathustra|1896|GfwAPg4rQQE?start=3|Richard Strauss|Also sprach Zarathustra",
"Hugo Wolf|Italienisches Liederbuch|1896|FwjVBdoVaoY|Hugo Wolf|Italienisches Liederbuch (Wolf)",
"Richard Strauss|Don Quixote|1897|5PvCGu2Ue0U|Richard Strauss|Don Quixote (Strauss)",
"Paul Dukas|The Sorcerer’s Apprentice|1897|xazobZ22zro?start=42|Paul Dukas|The Sorcerer's Apprentice (Dukas)",
"Richard Strauss|Ein Heldenleben|1898|Us1jfC7bMpA?start=3|Richard Strauss|Ein Heldenleben",
"Edward Elgar|Sea Pictures|1899|JlOU5St8Xc4?start=39|Edward Elgar|Sea Pictures",
"Edward Elgar|Enigma Variations|1899|vLNLvcBmoqo|Edward Elgar|Enigma Variations",
"Alexander Glazunov|The Seasons|1899|Pxf-urQe_AQ|Alexander Glazunov|The Seasons (ballet)",
"Arnold Schoenberg|Verklärte Nacht|1899|5h5Xc-rUef4|Arnold Schoenberg|Verklärte Nacht",
"Louis Vierne|Organ Symphonies|1899-1930|ilWwdPvEUgI|Louis Vierne|",
"Jean Sibelius|Symphony No. 1|1899|dCIw_4oJ4Gg|Jean Sibelius|Symphony No. 1 (Sibelius)",
"Giacomo Puccini|Tosca|1899|1SkBPCKiVqY|Giacomo Puccini|Tosca",
"Antonin Dvorak|Rusalka|1900|wPEDeWyWgw4|Antonín Dvořák|Rusalka (opera)",
"Edward Elgar|The Dream of Gerontius|1900|rnwmVypRY-g|Edward Elgar|The Dream of Gerontius",
"Gustav Mahler|Symphony No. 4|1900|YnfhInZLmUQ|Gustav Mahler|Symphony No. 4 (Mahler)",
"Jean Sibelius|Finlandia|1900|fE0RbPsC9uE|Jean Sibelius|Finlandia",
"Sergei Rachmaninoff|Piano Concerto No. 2|1901|rEGOihjqO9w|Sergei Rachmaninoff|Piano Concerto No. 2 (Rachmaninoff)",
"Sergei Rachmaninoff|Cello Sonata|1901|KkcJBjuCuPY|Sergei Rachmaninoff|Cello Sonata (Rachmaninoff)",
"Roger Quilter|Songs|1901-1939|cIj_NKN2eEI|Roger Quilter|",
"Francesco Cilea|Adriana Lecouvreur|1902|cWQ-uJBZkV8|Francesco Cilea|Adriana Lecouvreur",
"Gustav Mahler|Rückert Lieder|1902|zKpIZffBk-s?start=30|Gustav Mahler|Rückert-Lieder",
"Gustav Mahler|Symphony No. 5|1902|vOvXhyldUko|Gustav Mahler|Symphony No. 5 (Mahler)",
"Claude Debussy|Pelléas et Mélisande|1902|hpl_kIpKLzU|Claude Debussy|Pelléas et Mélisande (opera)",
"Carl Nielsen|Symphony No. 2, \"The Four Temperaments\"|1902|bq_c8Za33To|Carl Nielsen|Symphony No. 2 (Nielsen)",
"Hubert Parry|I Was Glad|1902|YeQYpsYTNoc|Hubert Parry|I was glad",
"Jean Sibelius|Symphony No. 2|1902|iXU8EXL7a_4?start=3|Jean Sibelius|Symphony No. 2 (Sibelius)",
"Eugen d’Albert|Tiefland|1903|Mqs4SA_Tyok|Eugen d'Albert|Tiefland (opera)",
"Maurice Ravel|String Quartet|1903|ieRQyyPowH0|Maurice Ravel|String Quartet (Ravel)",
"John Ireland|Songs|1903-1938|OLAK5uy_lrutKevCE1c4xJ2R9ocgudkaNMLnDnQBU|John Ireland (composer)|",
"Hugo Alfven|Swedish Rhapsodies|1903-1931|FN-n-UzG_dg|Hugo Alfvén|",
"Maurice Ravel|Shéhérazade|1903|paZ7LXd_wKM|Maurice Ravel|Shéhérazade (Ravel)",
"Richard Strauss|Symphonia domestica|1903|zvymcR85HPY|Richard Strauss|Symphonia Domestica",
"Alexander Zemlinsky|Die Seejungfrau|1903|gdxhgwey1J8|Alexander von Zemlinsky|Die Seejungfrau",
"Arnold Schoenberg|Pelleas und Melisande|1903|wis4ku1XBNg?start=3|Arnold Schoenberg|Pelleas und Melisande (Schoenberg)",
"Alexander Glazunov|Violin Concerto in A minor|1904|jq8oxIgyp8E|Alexander Glazunov|Violin Concerto (Glazunov)",
"Leos Janacek|Jenůfa|1904|DFbRCiChA1g|Leoš Janáček|Jenůfa",
"Anatoly Lyadov|Fairytales|1904-1909|FCIGLb0eiEY|Anatoly Lyadov|",
"Ferruccio Busoni|Piano Concerto|1904|ohPzurDZzZ4|Ferruccio Busoni|Piano Concerto (Busoni)",
"Gustav Mahler|Kindertotenlieder|1904|wXZMbRgbUvk?start=25|Gustav Mahler|Kindertotenlieder",
"Gustav Mahler|Symphony No. 6|1904|25tSq_dYL3c?start=3|Gustav Mahler|Symphony No. 6 (Mahler)",
"Alexander Scriabin|Symphony No. 3|1904|E-CdtD1Otx4|Alexander Scriabin|Symphony No. 3 (Scriabin)",
"Charles Villiers Stanford|Songs of the Sea|1904|bEljN59jR80|Charles Villiers Stanford|",
"Giacomo Puccini|Madama Butterfly|1904|IYrbdiee9SU|Giacomo Puccini|Madama Butterfly",
"Jean Sibelius|Violin Concerto|1905|J0w0t4Qn6LY|Jean Sibelius|Violin Concerto (Sibelius)",
"Maurice Ravel|Introduction and Allegro|1905|rv5vXFaKkIg|Maurice Ravel|Introduction and Allegro (Ravel)",
"Maurice Ravel|Miroirs|1905|FH92v4DoQuk?start=5|Maurice Ravel|Miroirs",
"Claude Debussy|La mer|1905|FOCucJw7iT8|Claude Debussy|La mer (Debussy)",
"Gustav Mahler|Symphony No. 7|1905|QdxvC7NNSLQ|Gustav Mahler|Symphony No. 7 (Mahler)",
"Franz Lehar|The Merry Widow|1905|9pUtRjDx2k8|Franz Lehár|The Merry Widow",
"Frederick Delius|A Mass of Life|1905|gg0aA0or6RU?start=870|Frederick Delius|A Mass of Life",
"Jean Sibelius|Pelléas et Mélisande Suite|1905|I06-fQMxxeo|Jean Sibelius|Pelléas et Mélisande (Sibelius)",
"Richard Strauss|Salome|1905|qLWbpv-I43M|Richard Strauss|Salome (opera)",
"Carl Nielsen|Maskarade|1906|lkpTewJR1wY|Carl Nielsen|Maskarade",
"Jean Sibelius|Pohjola’s Daughter|1906|faPICSQRQIw|Jean Sibelius|Pohjola's Daughter",
"Charles Ives|The Unanswered Question|1906-1935|WBiL0VEttZw?start=14|Charles Ives|The Unanswered Question",
"Arnold Schoenberg|Chamber Symphony No. 1|1906|m_hMVzPT9f4|Arnold Schoenberg|Chamber Symphony No. 1 (Schoenberg)",
"Josef Suk|Asrael Symphony|1906|wFoFxa7Hc04|Josef Suk|",
"Frederick Delius|Brigg Fair|1907|PMh2R4kRcFI|Frederick Delius|Brigg Fair",
"Gustav Mahler|Symphony No. 8|1907|nxf3xtH31jA|Gustav Mahler|Symphony No. 8 (Mahler)",
"Sergei Rachmaninoff|Symphony No. 2|1907|SvuitFzDxDg|Sergei Rachmaninoff|Symphony No. 2 (Rachmaninoff)",
"Nicolai Rimsky-Korsakov|The Golden Cockerel Suite|1907|ke5GjKYkAU0?start=25|Nikolai Rimsky-Korsakov|The Golden Cockerel",
"Edward Elgar|Symphony No. 1|1908|6SX9m2V9mbM|Edward Elgar|Symphony No. 1 (Elgar)",
"Maurice Ravel|Gaspard de la nuit|1908|f39a8rhk8mI|Maurice Ravel|Gaspard de la nuit",
"Isaac Albeniz|Iberia|1908|PLyrS5_ErY3KSrO3hP38Xi573XjseSDufe|Isaac Albéniz|Iberia (Albéniz)",
"Alexander Scriabin|The Poem of Ecstasy|1908|Ni87KKnYKHU?start=3|Alexander Scriabin|The Poem of Ecstasy",
"Maurice Ravel|Rapsodie espagnole|1908|bbIAPqQcWkQ?start=3|Maurice Ravel|Rapsodie espagnole",
"Arnold Schoenberg|String Quartet No. 2|1908|C-nFJ0SGim4|Arnold Schoenberg|String Quartets (Schoenberg)",
"Gustav Holst|Savitri|1908|5meFq1hxfDI|Gustav Holst|Sāvitri (opera)",
"Anton Webern|Passacaglia|1908|u37qhac1FUI|Anton Webern|Passacaglia (Webern)",
"Arnold Schoenberg|Erwartung|1908|P6PKIraXpIk|Arnold Schoenberg|Erwartung",
"Bela Bartok|String Quartets|1909-1939|PLaK7FcaVcs_wzQoa9ybz7QCAPRcunZfPR|Béla Bartók|List of string quartets by Béla Bartók",
"Gustav Mahler|Das Lied von der Erde|1909|Npy4gjZ81F0|Gustav Mahler|Das Lied von der Erde",
"Gustav Mahler|Symphony No. 9|1909|IoNEeKJ2x44|Gustav Mahler|Symphony No. 9 (Mahler)",
"Sergei Rachmaninoff|Piano Concerto No. 3|1909|1TJvJXyWDYw?start=21|Sergei Rachmaninoff|Piano Concerto No. 3 (Rachmaninoff)",
"Richard Strauss|Elektra|1909|jq1qfG0r4LE|Richard Strauss|Elektra (opera)",
"Arnold Schoenberg|Klavierstücke|1909-1931|cXU8ByUbrwM|Arnold Schoenberg|",
"George Butterworth|Songs|1909-1912|PLhHUg8xSoZUHxYeq8dAJoTOewOvP-Alw8|George Butterworth|",
"Sergei Rachmaninoff|The Isle of the Dead|1909|FcRn_2DgPlA?start=3|Sergei Rachmaninoff|Isle of the Dead (Rachmaninoff)",
"Arnold Schoenberg|Five Orchestral Pieces, Op. 16|1909|I9-_tVSrCqs|Arnold Schoenberg|",
"Jean Sibelius|String Quartet \"Voces intimae\"|1909|J5zlNd-djlw|Jean Sibelius|String Quartet (Sibelius)",
"Ralph Vaughan Williams|A Sea Symphony|1909-1923|2kR3FzJ1Hh4|Ralph Vaughan Williams|A Sea Symphony",
"Ralph Vaughan Williams|On Wenlock Edge|1909|nCJfWuqxN9A|Ralph Vaughan Williams|On Wenlock Edge (song cycle)",
"Anton Webern|Six Orchestral Pieces, Op. 6|1909|-EJLA8QAGCg|Anton Webern|",
"Claude Debussy|Préludes, Books 1 & 2|1910-1913|MWkxPtFS10I|Claude Debussy|Préludes (Debussy)",
"Engelbert Humperdinck|Königskinder|1910|3FU-sbfd9j4|Engelbert Humperdinck (composer)|Königskinder",
"Gustav Mahler|Symphony No. 10|1910|vHyV8noUXC0|Gustav Mahler|Symphony No. 10 (Mahler)",
"Edward Elgar|Violin Concerto|1910|Lmr4U5f_3qg?start=37|Edward Elgar|Violin Concerto (Elgar)",
"Florent Schmitt|La tragédie de Salomé|1910|fmRCZQ2vID4?start=3|Florent Schmitt|",
"Fritz Kreisler|Liebesfreund & Liebesleid|1910|-QQOc2NGe-0|Fritz Kreisler|Alt-Wiener Tanzweisen",
"Franz Schreker|Der ferne Klang|1910|wgYr2weuhC0|Franz Schreker|Der ferne Klang",
"Alexander Scriabin|Prometheus|1910|10ESN_t7txI?start=45|Alexander Scriabin|Prometheus: The Poem of Fire",
"Richard Strauss|Der Rosenkavalier|1910|I8X64WJq6qc?start=111|Richard Strauss|Der Rosenkavalier",
"Ralph Vaughan Williams|Fantasia on a Theme by Thomas Tallis|1910-1919|ihx5LCF1yJY|Ralph Vaughan Williams|Fantasia on a Theme by Thomas Tallis",
"Igor Stravinsky|The Firebird|1910|RZkIAVGlfWk|Igor Stravinsky|The Firebird",
"Edward Elgar|Symphony No. 2|1911|CY7vaUhxhDY|Edward Elgar|Symphony No. 2 (Elgar)",
"Enrique Granados|Goyescas|1911|s0aVTPvYQ4Y|Enrique Granados|",
"Maurice Ravel|Ma mère l’oye|1911|N_ENSdLOblk?start=3|Maurice Ravel|",
"Bela Bartok|Bluebeard’s Castle|1911|p9Aq2WWds8k|Béla Bartók|",
"Jean Sibelius|Symphony No. 4|1911|HjeF99_ocfM|Jean Sibelius|Symphony No. 4 (Sibelius)",
"Sergey Taneyev|Piano Quintet|1911|YfU3iOKlH0w|Sergei Taneyev|",
"Sergei Rachmaninoff|Études-tableaux|1911|KGniWXjsdu4|Sergei Rachmaninoff|Études-Tableaux, Op. 33",
"Carl Nielsen|Symphony No. 3|1911|40-1Ww-uXJk|Carl Nielsen|Symphony No. 3 (Nielsen)",
"Reinhold Glière|Symphony No. 3 \"Ilya Muromets\"|1911|WRpEt9FvTbU|Reinhold Glière|Symphony No. 3 (Glière)",
"Arnold Schoenberg|Gurrelieder|1911|OLAK5uy_mmKJ9H_rxGSFWX2Fo-Ic89afeWRWp6ciI|Arnold Schoenberg|Gurre-Lieder",
"Igor Stravinsky|Petrushka|1911|esD90diWZds|Igor Stravinsky|Petrushka (ballet)",
"Sergei Prokofiev|Piano Concerto No. 1|1912|JqCwQ9clHec|Sergei Prokofiev|Piano Concerto No. 1 (Prokofiev)",
"Maurice Ravel|Daphnis et Chloé|1912|O4lzPz3NnI0|Maurice Ravel|Daphnis et Chloé",
"Sergei Rachmaninoff|Vocalise and Other Songs|1912|PL-Mm0pfOCJhslJBIadTDYBTLPAvZYfwms|Sergei Rachmaninoff|Vocalise (Rachmaninoff)",
"Arnold Schoenberg|Pierrot lunaire|1912|bd2cBUJmDr8|Arnold Schoenberg|Pierrot lunaire",
"Sergei Rachmaninoff|Piano Sonata No. 2|1913-1931|TsafFhTMrVM|Sergei Rachmaninoff|Piano Sonata No. 2 (Rachmaninoff)",
"Wilhelm Stenhammar|Serenade|1913|h0RSG4RCQJM|Wilhelm Stenhammar|",
"Claude Debussy|Jeux|1913|rABBmzI4HQU|Claude Debussy|Jeux",
"Edward Elgar|Falstaff|1913|8yM0c2J4x7g|Edward Elgar|Falstaff (Elgar)",
"Ivor Gurney|Songs|1913-1922|OLAK5uy_k7esdHOvPbw1bItEKZ7mEh7kcs6KT74lA|Ivor Gurney|",
"Sergei Rachmaninoff|The Bells|1913|fvy0nN5t0Po?start=36|Sergei Rachmaninoff|The Bells (symphony)",
"Albert Roussel|Le festin de l’araignée|1913|RufoBzyv7Iw|Albert Roussel|The Spider's Feast",
"Igor Stravinsky|The Rite of Spring|1913|EkwqPJZe8ms|Igor Stravinsky|",
"Ralph Vaughan Williams|A London Symphony|1913-1933|0Uv4lJsu0Jw|Ralph Vaughan Williams|A London Symphony",
"Erno Dohnanyi|Variations on a Nursery Tune|1914|Bqx4oYOy85o|Ernst von Dohnányi|Variations on a Nursery Tune (Dohnányi)",
"Manuel de Falla|Siete canciones populares Españolas|1914|PLm0qx3c_LrRTlIB8021pET_m-2pbgatyP|Manuel de Falla|Siete canciones populares españolas",
"Max Reger|Variations and Fugue on a Theme of Mozart|1914|2Uo0sm9mtR0|Max Reger|Variations and Fugue on a Theme by Mozart",
"Ralph Vaughan Williams|The Lark Ascending|1914-1920|IOWN5fQnzGk|Ralph Vaughan Williams|The Lark Ascending (Vaughan Williams)",
"Zoltan Kodaly|Duo for Violin and Cello|1914|ihgPqrukvLc|Zoltán Kodály|",
"Maurice Ravel|Piano Trio|1914|3QzLA5se4co|Maurice Ravel|Piano Trio (Ravel)",
"Bela Bartok|Romanian Folk Dances|1915|Z50Ooqv1GFg|Béla Bartók|Romanian Folk Dances",
"Claude Debussy|Douze Études|1915|PLfgs3d6ZAQnDAZyg_L62cppweKvvuJfnu|Claude Debussy|Études (Debussy)",
"Alban Berg|Three Orchestral Pieces, Op. 6|1915-1929|q6U8AqRNyU8|Alban Berg|Three Pieces for Orchestra (Berg)",
"Manuel de Falla|Nights in the Gardens of Spain|1915|yo9DJB6wYy8?start=3|Manuel de Falla|Nights in the Gardens of Spain",
"Claude Debussy|Sonatas|1915-1917|6p1HDpf48Tg|Claude Debussy|Six sonatas for various instruments",
"Manuel de Falla|El amor brujo|1915-1925|V3XfmRZAQ-o|Manuel de Falla|El amor brujo",
"Charles Ives|Concord Sonata|1915|cDNPpsUaVYo|Charles Ives|Piano Sonata No. 2 (Ives)",
"Hans Pfitzner|Palestrina|1915|OLAK5uy_nDbNHHjXFGzaXM9ujUZiiLJgmNAUIw1no|Hans Pfitzner|Palestrina (opera)",
"Franz Schreker|Die Gezeichneten|1915|1tdzUBIXDXg|Franz Schreker|",
"Sergei Rachmaninoff|All-Night Vigil (Vesper)|1915|U2NSfTXjEPI|Sergei Rachmaninoff|All-Night Vigil (Rachmaninoff)",
"Wilhelm Stenhammar|Symphony No. 2|1915|pLrPf1OEtxE|Wilhelm Stenhammar|",
"Richard Strauss|Eine Alpensinfonie|1915|zsTo7QxxgYg?start=3|Richard Strauss|",
"Karol Szymanowski|Myths|1915|M5UJmxd3ixo|Karol Szymanowski|",
"Jean Sibelius|Symphony No. 5|1915-1919|RRS6dIgn_QI|Jean Sibelius|Symphony No. 5 (Sibelius)",
"Ernest Bloch|Schelomo|1916|RRGMPCXS_yM?start=3|Ernest Bloch|Schelomo",
"Karol Szymanowski|Symphony No. 3, \"The Song of the Night\"|1916|LFExkkNdVCc|Karol Szymanowski|Symphony No. 3 (Szymanowski)",
"Karol Szymanowski|Violin Concerto No. 1|1916|uT00G955oUg|Karol Szymanowski|Violin Concerto No. 1 (Szymanowski)",
"Percy Grainger|In a Nutshell|1916|nZxMHMx4X1o|Percy Grainger|In a Nutshell",
"Ottorino Respighi|Roman Trilogy|1916-1928|dWpQkNxGoGE|Ottorino Respighi|",
"Carl Nielsen|Symphony No. 4, \"The Inextinguishable\"|1916|IC0Lf03sGw4|Carl Nielsen|Symphony No. 4 (Nielsen)",
"Richard Strauss|Ariadne auf Naxos|1916|VugbX5UgrLY|Richard Strauss|Ariadne auf Naxos",
"Charles Ives|Symphony No. 4|1916|aMT_EGXQwyk|Charles Ives|Symphony No. 4 (Ives)",
"Gustav Holst|The Planets|1917|HP5xhyPn58U?start=3|Gustav Holst|The Planets",
"Lili Boulanger|Psalm 130, \"Du fond de l’abîme\"|1917|kS87JdcQSfA?start=4|Lili Boulanger|",
"Sergei Prokofiev|Violin Concerto No. 1|1917|SyFQwiAqDS4|Sergei Prokofiev|Violin Concerto No. 1 (Prokofiev)",
"Sergei Prokofiev|Symphony No. 1|1917|CXO-hB6jNTI|Sergei Prokofiev|Symphony No. 1 (Prokofiev)",
"Erik Satie|Parade|1917|IuZ4DYywqpw|Erik Satie|Parade (ballet)",
"Richard Strauss|Die Frau ohne Schatten|1917|SkaOIpdBb2M?start=3|Richard Strauss|Die Frau ohne Schatten",
"Ottorino Respighi|Ancient Airs and Dances|1917-1932|OLAK5uy_meJO_rpkpLEBgbcDUu_BYNs0WxpxXnRS8|Ottorino Respighi|Ancient Airs and Dances",
"George Enescu|Symphony No. 3|1918|_7kohi6by-I|George Enescu|Symphony No. 3 (Enescu)",
"Francis Poulenc|Mélodies|1918-1960|LnMIqM0Z918|Francis Poulenc|Mélodie",
"Leos Janacek|Taras Bulba|1918|VOG-YDbe3JA|Leoš Janáček|Taras Bulba (rhapsody)",
"Giacomo Puccini|Gianni Schicchi|1918|GcH-2uHqLBs?start=182|Giacomo Puccini|Gianni Schicchi",
"Igor Stravinsky|The Soldier’s Tale|1918|OLAK5uy_kDYt5a9OPWWeeGRTpWuFMmrBMHjfunS_E|Igor Stravinsky|L'Histoire du soldat",
"Arnold Bax|Tintagel|1919|vZmRljEyIOY?start=25|Arnold Bax|Tintagel (Bax)",
"Manuel de Falla|The Three-Cornered Hat|1919|Al68zeQQHlg|Manuel de Falla|The Three-Cornered Hat",
"Edward Elgar|Cello Concerto|1919|lNVe_1Eb5dw|Edward Elgar|Cello Concerto (Elgar)",
"Darius Milhaud|Le boeuf sur le toit|1919|ExriOKRjNWI|Darius Milhaud|Le Bœuf sur le toit",
"Sergei Prokofiev|The Love for Three Oranges|1919|PL95E187E5F26BD59F|Sergei Prokofiev|The Love for Three Oranges",
"Maurice Ravel|Le tombeau du Couperin|1919|7NA4j3VhGY4?start=3|Maurice Ravel|",
"Joaquin Turina|Danzas fantásticas|1920|gLzU3-YvzPc?start=28|Joaquín Turina|Danzas fantásticas",
"Erich Wolfgang Korngold|Die tote Stadt|1920|OLAK5uy_kMRfAd22FD9yjsNQFAQcQVi7majisfVtQ|Erich Wolfgang Korngold|Die tote Stadt",
"Maurice Ravel|La valse|1920|TMSgWhIENSk|Maurice Ravel|",
"Igor Stravinsky|Pulcinella|1920|funlnfTpAbI|Igor Stravinsky|Pulcinella (ballet)",
"Igor Stravinsky|Symphonies of Wind Instruments|1920-1947|72V_OTSiAkM|Igor Stravinsky|Symphonies of Wind Instruments",
"Federico Mompou|Cançons i danses|1921-1979|0CzRGlpUWh8|Federico Mompou|Cançons i danses",
"Bela Bartok|Violin Sonatas nos. 1 & 2|1921-1922|b_C9qQhApvE|Béla Bartók|",
"Leos Janacek|Kátya Kabanová|1921|Gti-Gqj0asY|Leoš Janáček|",
"Erwin Schulhoff|Suite for Chamber Orchestra|1921|cXpWcBKBoKc?start=15|Erwin Schulhoff|",
"Charles Ives|Three Places in New England|1921|kP0yMg6_Yaw|Charles Ives|Three Places in New England",
"Edgard Varèse|Amériques|1921-1927|Upo5FStElCc|Edgard Varèse|",
"Sergei Prokofiev|Piano Concerto No. 3|1921|BS0SwRoYAW0|Sergei Prokofiev|Piano Concerto No. 3 (Prokofiev)",
"Edgard Varèse|Offrandes|1921|1L7VquPejbw|Edgard Varèse|",
"Igor Stravinsky|Three Movements from \"Petrushka\"|1921|4Y3n2oJG7q0|Igor Stravinsky|Trois mouvements de Petrouchka",
"Arthur Bliss|A Colour Symphony|1922-1932|zi6FdphM7CA|Arthur Bliss|",
"Maurice Ravel|Sonata for Violin and Cello|1922|szPF0KhxYIs|Maurice Ravel|",
"William Walton|Façade|1922-1951|79ahguBURn4|William Walton|Façade (entertainment)",
"Peter Warlock|The Curlew|1922|2JqOm9dnwdU|Peter Warlock|The Curlew",
"Jacques Ibert|Escales|1922|VQm0bfVQtsg?start=3|Jacques Ibert|",
"Carl Nielsen|Symphony No. 5|1922|lH2MijVKz9Y|Carl Nielsen|Symphony No. 5 (Nielsen)",
"Alban Berg|Wozzeck|1922|jVmWimEX1gw|Alban Berg|Wozzeck",
"Bela Bartok|Dance Suite|1923|nI1XE5ns3H8|Béla Bartók|Dance Suite (Bartók)",
"Joseph Canteloube|Chants d’Auvergne|1923-1954|PL1IXBSY4jc2s3ulYvnoPaPiRPFgKC23wf|Joseph Canteloube|Chants d'Auvergne",
"Leos Janacek|String Quartets nos. 1 & 2|1923-1928|y5wvFZDj37k|Leoš Janáček|String Quartet No. 1 (Janáček)",
"Arthur Honegger|Three Symphonic Movements|1923-1933|R88o18b7Pk8|Arthur Honegger|",
"Darius Milhaud|La création du monde|1923|nWpAQ6AWMDA|Darius Milhaud|La création du monde",
"Leos Janacek|The Cunning Little Vixen|1923|q2pbTAeZFrg|Leoš Janáček|The Cunning Little Vixen",
"Francis Poulenc|Les biches|1923-1947|LxLUiYgU0m0|Francis Poulenc|Les biches",
"Arnold Schoenberg|Suite for Piano|1923|TVWbtaZFVjA|Arnold Schoenberg|Suite for Piano (Schoenberg)",
"Igor Stravinsky|Octet|1923|YyqLnP0hOnI|Igor Stravinsky|",
"Alexander Zemlinsky|Lyric Symphony|1923|KGvMhAmBniE|Alexander von Zemlinsky|Lyric Symphony",
"Igor Stravinsky|Les noces|1923|gNBDJNHeZmo|Igor Stravinsky|Les noces",
"Eugène Ysaye|Six Solo Violin Sonatas, Op. 27|1923|PL5KxEyxTsMyddnmn_Ch1OYr1q56eJUFh6|Eugène Ysaÿe|Six Sonatas for solo violin (Ysaÿe)",
"Bela Bartok|The Miraculous Mandarin|1924|SCkn0Qjm0Ho|Béla Bartók|The Miraculous Mandarin",
"Ferruccio Busoni|Doktor Faust|1924|xrFwfeKzRuE|Ferruccio Busoni|Doktor Faust",
"Karol Szymanowski|King Roger|1924|rguMf64vWW4|Karol Szymanowski|King Roger",
"Jean Sibelius|Symphony No. 7|1924|Bi9QiDrJJmw?start=3|Jean Sibelius|Symphony No. 7 (Sibelius)",
"George Gershwin|Rhapsody in Blue|1924|ynEOo28lsbc|George Gershwin|Rhapsody in Blue",
"Marcel Dupré|Symphonie-Passion|1924|BrKyBkssfWA|Marcel Dupré|",
"Maurice Ravel|Tzigane|1924|tQjh9Z71RJ4?start=3|Maurice Ravel|Tzigane",
"Maurice Ravel|L’enfant et les sortilèges|1924|JbqySviU4YQ|Maurice Ravel|",
"Alexander Zemlinsky|String Quartet No. 3|1924|fLMnvibmql8|Alexander von Zemlinsky|Late string quartets (Beethoven)",
"Giacomo Puccini|Turandot|1924|cWc7vYjgnTs|Giacomo Puccini|Turandot",
"Carl Nielsen|Symphony No. 6|1925|SRLT5vq1weM?start=3|Carl Nielsen|Symphony No. 6 (Nielsen)",
"Dmitri Shostakovich|Symphony No. 1|1925|bPQMdtAOXVw?start=3|Dmitri Shostakovich|Symphony No. 1 (Shostakovich)",
"George Enescu|Violin Sonata No. 3|1926|Yk5N59Kuz8k|George Enescu|Violin Sonata No. 3 (Enescu)",
"Frank Martin|Mass for double choir|1926|J4c0ecGbtqY|Frank Martin (composer)|",
"Sergei Rachmaninoff|Piano Concerto No. 4|1926-1941|rhL2qQKE4CU?start=5|Sergei Rachmaninoff|Piano Concerto No. 4 (Rachmaninoff)",
"Karol Szymanowski|Mazurkas|1926-1934|fjjoZ0yFB6k|Karol Szymanowski|",
"Karol Szymanowski|Stabat Mater|1926|ds4lcWa9aB4|Karol Szymanowski|Stabat Mater (Szymanowski)",
"Leos Janacek|Sinfonietta|1926|9aFTv50AoEQ|Leoš Janáček|Sinfonietta (Janáček)",
"Maurice Ravel|Chansons madécasses|1926|bb1Swd9xrl0|Maurice Ravel|Chansons madécasses",
"Jean Sibelius|Tapiola|1926|gkX-Uc0e3TQ?start=5|Jean Sibelius|Tapiola (Sibelius)",
"Maurice Ravel|Violin Sonata|1927|OFbffshku0k|Maurice Ravel|Violin Sonata No. 2 (Ravel)",
"Gustav Holst|Egdon Heath|1927|meaYfLfnjZw|Gustav Holst|Egdon Heath (Holst)",
"Leos Janacek|Glagolitic Mass|1927|wVRLoUknC9o|Leoš Janáček|Glagolitic Mass",
"Joseph Jongen|Symphonie concertante|1927|oePjCCDd_A4?start=7|Joseph Jongen|",
"Bohuslav Martinu|La revue de cuisine|1927|B73RwTsrikQ|Bohuslav Martinů|La revue de cuisine",
"Igor Stravinsky|Oedipus rex|1927|O0vVLj-9y7o|Igor Stravinsky|Oedipus rex (opera)",
"Zoltan Kodaly|Háry János Suite|1927|ym2QvHQNyPU?start=25|Zoltán Kodály|Háry János",
"Eugene Goossens|Oboe Concerto|1927|_GZbiMIcml8|Eugene Aynsley Goossens|",
"Constant Lambert|The Rio Grande|1927|_I1eHvdwdv4|Constant Lambert|The Rio Grande (Lambert)",
"Edgard Varèse|Arcana|1927|Bg3-Sdn4PPg|Edgard Varèse|",
"George Gershwin|An American in Paris|1928|K4I2OzMltM4?start=3|George Gershwin|An American in Paris",
"Maurice Ravel|Boléro|1928|r30D3SW4OVw|Maurice Ravel|Boléro",
"Arnold Schoenberg|Variations for Orchestra|1928|iL1XzH6gpAY|Arnold Schoenberg|",
"Igor Stravinsky|Apollo|1928|xfn8ieMI6V4?start=6|Igor Stravinsky|Apollo (ballet)",
"Kurt Weill|Das Berliner Requiem|1928|QxYbcNJHv_o|Kurt Weill|The Berlin Requiem (Weill)",
"Kurt Weill|The Threepenny Opera|1928|PLjA79Xk8j1xgH7aT2gusAByfAQaL6G6yO|Kurt Weill|The Threepenny Opera",
"Arnold Bax|Symphony No. 3|1929|OLAK5uy_nfqTByqwj7mqZotuQ48-zoFq11_UEtkQE|Arnold Bax|Symphony No. 3 (Bax)",
"William Walton|Viola Concerto|1929-1961|ozL-R0yWhPs|William Walton|Viola Concerto (Walton)",
"Frank Bridge|Oration|1930|UurMi-JW_pQ|Frank Bridge|",
"Albert Roussel|Symphony No. 3|1930|00n4z_AuLiI|Albert Roussel|",
"Igor Stravinsky|Symphony of Psalms|1930|DqWZGUO_eoc|Igor Stravinsky|Symphony of Psalms",
"Maurice Ravel|Piano Concerto for the Left Hand|1930|ZbEtk1kdYx4|Maurice Ravel|Piano Concerto for the Left Hand (Ravel)",
"Kaikhosru Shapurji Sorabji|Opus clavicembalisticum|1930|OLAK5uy_mJXjeW38xqgrzLuhw_Vlc8ZIJbxhcFV_I|Kaikhosru Shapurji Sorabji|Opus clavicembalisticum",
"Ralph Vaughan Williams|Job|1930|GlGjFynWFUw|Ralph Vaughan Williams|Job: A Masque for Dancing",
"William Walton|Belshazzar’s Feast|1931-1957|_HVgxgC2ZEk|William Walton|",
"Igor Stravinsky|Violin Concerto|1931|Wn6K53W_Nu0?start=3|Igor Stravinsky|Violin Concerto (Stravinsky)",
"Maurice Ravel|Piano Concerto in G major|1931|gAtzmCGMNfI|Maurice Ravel|Piano Concerto in G major (Ravel)",
"Bela Bartok|Piano Concerto No. 2|1931|jOHl_X_OoIk|Béla Bartók|Piano Concerto No. 2 (Bartók)",
"Edgard Varese|Ionisation|1931|wClwaBuFOJA|Edgard Varèse|",
"Francis Poulenc|Concerto for Two Pianos|1932|2-VSj7bSsfo|Francis Poulenc|Concerto for Two Pianos and Orchestra (Poulenc)",
"Francis Poulenc|Sextet|1932-1939|CGtDGYU9Dos|Francis Poulenc|Sextet (Poulenc)",
"Richard Strauss|Arabella|1932|C9MrIY3aAPA|Richard Strauss|Arabella",
"Igor Stravinsky|Duo Concertant|1932|jZXRCL3_Ads|Igor Stravinsky|Duo Concertant",
"Arnold Schoenberg|Moses und Aron|1932|5nD36ZpRyKU|Arnold Schoenberg|Moses und Aron",
"Dmitri Shostakovich|Lady Macbeth of Mtsensk|1932|7Mf6Q3m7erI?start=40|Dmitri Shostakovich|Lady Macbeth of Mtsensk (opera)",
"Karol Szymanowski|Symphony No. 4|1932|kjJyKrd0yhc|Karol Szymanowski|Symphony No. 4 (Szymanowski)",
"Charles Tournemire|L’orgue mystique|1932|OLAK5uy_m_aEG0NBz9esX02rojldUBV0Pu-Ziu4KM|Charles Tournemire|",
"Dmitri Shostakovich|Piano Concerto No. 1|1933|WyADlfFSFC0|Dmitri Shostakovich|Piano Concerto No. 1 (Shostakovich)",
"Kurt Weill|The Seven Deadly Sins|1933|PLs2vq238vU6ljW9CYM9Xk22GLbT0Kr4mx|Kurt Weill|The Seven Deadly Sins (ballet chanté)",
"Zoltan Kodaly|Dances of Galánta|1933|Gi_gUeCG_d8|Zoltán Kodály|Dances of Galánta",
"Karol Szymanowski|Violin Concerto No. 2|1933|roFFn0DL_hU|Karol Szymanowski|Violin Concerto No. 2 (Szymanowski)",
"Edward Elgar|Symphony No. 3|1934|Tnor-Hg7Utc|Edward Elgar|Symphony No. 3 (Elgar)",
"Dmitri Shostakovich|Cello Sonata|1934|DBYoug7MTZQ|Dmitri Shostakovich|Cello Sonata (Shostakovich)",
"Sergei Prokofiev|Lieutenant Kijé Suite|1934|YbaY7p5ahZo|Sergei Prokofiev|https://en.wikipedia.org/wiki/Lieutenant_Kij%C3%A9_(Prokofiev)#Suite",
"Sergei Rachmaninoff|Rhapsody on a Theme of Paganini|1934|ppJ5uITLECE?start=4|Sergei Rachmaninoff|Rhapsody on a Theme of Paganini",
"Paul Hindemith|Mathis der Maler Symphony|1934|znXWfmfPh8E|Paul Hindemith|Symphony: Mathis der Maler",
"Ralph Vaughan Williams|Symphony No. 4|1934|QMG70e0Usn0?start=167|Ralph Vaughan Williams|Symphony No. 4 (Vaughan Williams)",
"Sergei Prokofiev|Romeo and Juliet|1935|7qqrIusxVAI?start=4|Sergei Prokofiev|Romeo and Juliet (Prokofiev)",
"Alban Berg|Lulu|1935|bLuLsFjnCjI|Alban Berg|Lulu (opera)",
"William Walton|Symphony No. 1|1935|R3MNvdEbvik|William Walton|Symphony No. 1 (Walton)",
"Alban Berg|Violin Concerto|1935|8-srlUzphpE?start=3|Alban Berg|Violin Concerto (Berg)",
"George Gershwin|Porgy and Bess|1935|Vi2IWu-C2ds?start=3|George Gershwin|",
"Sergei Prokofiev|Violin Concerto No. 2|1935|jMQAbX0xO90?start=30|Sergei Prokofiev|Violin Concerto No. 2 (Prokofiev)",
"Samuel Barber|Adagio for Strings|1936|WAoLJ8GbA4Y?start=6|Samuel Barber|Adagio for Strings",
"Carl Orff|Carmina burana|1936|QEllLECo4OM?start=82|Carl Orff|Carmina Burana (Orff)",
"Sergei Prokofiev|Peter and the Wolf|1936|px8FakwGPDM|Sergei Prokofiev|Peter and the Wolf",
"Olivier Messiaen|Poèmes pour Mi|1936|l_InFMyiyn8|Olivier Messiaen|Poèmes pour Mi",
"Sergei Rachmaninoff|Symphony No. 3|1936|u3VnQRMh-IA|Sergei Rachmaninoff|Symphony No. 3 (Rachmaninoff)",
"Anton Webern|Variations, Op. 27|1936|ZEtqEzPakxA|Anton Webern|Variations for piano (Webern)",
"Bela Bartok|Music for Strings, Percussion, and Celesta|1936|HGJcsTtJ188|Béla Bartók|Music for Strings, Percussion and Celesta",
"Dmitri Shostakovich|Symphony No. 4|1936|HQrhffGoy2E|Dmitri Shostakovich|Symphony No. 4 (Shostakovich)",
"Franz Schmidt|The Book with Seven Seals|1937|gQfMFH7UU7s|Franz Schmidt (composer)|The Book with Seven Seals",
"Benjamin Britten|Variations on a Theme of Frank Bridge|1937|_TkHXHH0w0Q|Benjamin Britten|Variations on a Theme of Frank Bridge",
"Dmitri Shostakovich|Symphony No. 5|1937|cg0M4LzEITQ?start=3|Dmitri Shostakovich|Symphony No. 5 (Shostakovich)",
"Richard Strauss|Daphne|1937|OwQ6wmcYGiY|Richard Strauss|Daphne (opera)",
"Dag Wiren|Serenade for Strings|1937|z4jZ4fIjSWU?start=3|Dag Wirén|",
"Francis Poulenc|Organ Concerto|1938|HsFsBNAmCd0?start=3|Francis Poulenc|",
"Bela Bartok|Violin Concerto No. 2|1938|KbAaM9tIYhs|Béla Bartók|",
"Herbert Howells|Hymnus Paradisi|1938|l4Tlik9vfJ0?start=42|Herbert Howells|Hymnus Paradisi",
"Bohuslav Martinu|Double Concerto|1938|4BLJxJG1kQo|Bohuslav Martinů|Double Concerto for Two String Orchestras, Piano, and Timpani",
"Roy Harris|Symphony No. 3|1938|cvHF04mN64c|Roy Harris|Symphony No. 3",
"Ralph Vaughan Williams|Serenade to Music|1938|Ja-fD7zLllQ|Ralph Vaughan Williams|Serenade to Music",
"Silvestre Revueltas|Sensemayá|1938|aJxd0nIY1oA|Silvestre Revueltas|Sensemayá",
"Igor Stravinsky|Concerto in E flat, \"Dumbarton Oaks\"|1938|l6gqiA8iIMo|Igor Stravinsky|Violin Concerto (Stravinsky)",
"Anton Webern|String Quartet, Op. 28|1938|5r29_vMzRF8|Anton Webern|String Quartet (Webern)",
"Benjamin Britten|Les illuminations|1939|QexU2At_lLQ|Benjamin Britten|Les Illuminations (Britten)",
"Benjamin Britten|Violin Concerto|1939|dDTIae06t6Y|Benjamin Britten|Violin Concerto (Britten)",
"Joaquín Rodrigo|Concierto de Aranjuez|1939|-oxH-7VklBI|Joaquín Rodrigo|Concierto de Aranjuez",
"Dmitri Shostakovich|Symphony No. 6|1939|B8euxavGpps|Dmitri Shostakovich|Symphony No. 6 (Shostakovich)",
"Michael Tippett|Concerto for Double String Orchestra|1939|_5ihd3NYK3E|Michael Tippett|Concerto for Double String Orchestra (Tippett)",
"Sergei Prokofiev|Alexander Nevsky|1939|Gq4PaJfod4w|Sergei Prokofiev|Alexander Nevsky (Prokofiev)",
"William Walton|Violin Concerto|1939-1943|elCxwrGAoVs?start=47|William Walton|Violin Concerto (Walton)",
"Samuel Barber|Violin Concerto|1940|MdRD6gEa9CY|Samuel Barber|Violin Concerto (Barber)",
"Benjamin Britten|Sinfonia da Requiem|1940|IZAgYQSTTJA|Benjamin Britten|Sinfonia da Requiem",
"Dmitri Shostakovich|Piano Quintet|1940|0nRd0ANdcKI?start=218|Dmitri Shostakovich|Piano Quintet (Shostakovich)",
"Sergei Prokofiev|Piano Sonata No. 6|1940|p9GzBjB-YpA|Sergei Prokofiev|Piano Sonata No. 6 (Prokofiev)",
"Aram Khachaturian|Violin Concerto|1940|rixdcNMGwWQ|Aram Khachaturian|Violin Concerto (Khachaturian)",
"Igor Stravinsky|Symphony in C|1940|bmnfwnfnKBA|Igor Stravinsky|Symphony in C (Stravinsky)",
"Sergei Rachmaninoff|Symphonic Dances|1940|otJmf3pyb1E|Sergei Rachmaninoff|Symphonic Dances (Rachmaninoff)",
"Arthur Honegger|Symphony No. 2|1941|NfssYoRkY58|Arthur Honegger|Symphony No. 2 (Honegger)",
"Olivier Messiaen|Quartet for the End of Time|1941|zYpBHc8px_U|Olivier Messiaen|Quatuor pour la fin du temps",
"Benjamin Britten|String Quartets|1941-1975|SdKcOm_3VJU|Benjamin Britten|String Quartet No. 2 (Britten)",
"Manuel Ponce|Concierto del Sur|1941|0OoFTYM-J2c|Manuel Ponce|Concierto del Sur",
"Richard Strauss|Capriccio|1941|nnDcVSDnSU4|Richard Strauss|Capriccio (opera)",
"Michael Tippett|A Child of Our Time|1941|OLAK5uy_ncVeCFyYKFlGIKzr-jTC7TKPddGQgMbNE|Michael Tippett|A Child of Our Time",
"Alberto Ginastera|Estancia|1941|fnb5byOyXyM|Alberto Ginastera|Estancia (Ginastera)",
"Dmitri Shostakovich|Symphony No. 7, \"Leningrad\"|1941|GB3zR_X25UU?start=29|Dmitri Shostakovich|Symphony No. 7 (Shostakovich)",
"Maurice Durufle|Prélude et fugue sur le nom d’Alain|1942|Or147RQSBOM|Maurice Duruflé|",
"Aaron Copland|Rodeo|1942|du4DrdGp9vM|Aaron Copland|Rodeo (ballet)",
"Gerald Finzi|Let Us Garlands Bring|1942|ASSoVAFsx4M|Gerald Finzi|Let Us Garlands Bring (Finzi)",
"Sergei Prokofiev|Piano Sonata No. 7|1942|h21KSLqj7HA|Sergei Prokofiev|Piano Sonata No. 7 (Prokofiev)",
"Arnold Schoenberg|Piano Concerto|1942|977xqcl8DnE|Arnold Schoenberg|",
"Richard Strauss|Horn Concerto No. 2|1942|wCPEZqIGnmA|Richard Strauss|Horn Concerto No. 2 (Strauss)",
"Benjamin Britten|Serenade for Tenor, Horn, and Strings|1943|gcnw-jBCpPw|Benjamin Britten|Serenade for Tenor, Horn and Strings",
"Sergei Prokofiev|War and Peace|1943-1952|L50YIs955e0|Sergei Prokofiev|War and Peace (opera)",
"Ralph Vaughan Williams|Symphony No. 5|1943|LsQGFlcqUmA?start=3|Ralph Vaughan Williams|Symphony No. 5 (Vaughan Williams)",
"Bela Bartok|Concerto for Orchestra|1943-1945|pG26BMDVR9E?start=3|Béla Bartók|Concerto for Orchestra (Bartók)",
"Paul Hindemith|Symphonic Metamorphosis of Themes by Carl Maria von Weber|1943|2A8tUpPRyR4|Paul Hindemith|Symphonic Metamorphosis of Themes by Carl Maria von Weber",
"Dmitri Shostakovich|Symphony No. 8|1943|9CaXNxh8msw|Dmitri Shostakovich|Symphony No. 8 (Shostakovich)",
"Aaron Copland|Appalachian Spring|1944|Q4Qt0AIRK-0|Aaron Copland|Appalachian Spring",
"Sergei Prokofiev|Cinderella|1944|LPbKZXNfJ-Y|Sergei Prokofiev|Cinderella (Prokofiev)",
"Sergei Prokofiev|Symphony No. 5|1944|AWWxGl1X4v0?start=20|Sergei Prokofiev|Symphony No. 5 (Prokofiev)",
"Dmitri Shostakovich|Piano Trio No. 2|1944|KgVvUHxKb58|Dmitri Shostakovich|",
"Leonard Bernstein|On the Town|1944|CBdP8td0sto|Leonard Bernstein|On the Town (musical)",
"Olivier Messiaen|Vingt regards sur l’Enfant-Jésus|1944|ovMnmIoZh74|Olivier Messiaen|",
"Benjamin Britten|Peter Grimes|1945|VTd2aXLTA84|Benjamin Britten|Peter Grimes",
"Bela Bartok|Piano Concerto No. 3|1945|l7J7L53b8U0|Béla Bartók|Piano Concerto No. 3 (Bartók)",
"Erich Wolfgang Korngold|Violin Concerto|1945|lcGEGl5bdbk|Erich Wolfgang Korngold|Violin Concerto (Korngold)",
"Bela Bartok|Viola Concerto|1945|yfpCCJqu4Ts|Béla Bartók|Viola Concerto (Bartók)",
"Frank Martin|Petite symphonie concertante|1945|hTkbjOzsLCI|Frank Martin (composer)|Petite symphonie concertante",
"Bohuslav Martinu|Symphony No. 4|1945|2r-YJbhvhfM|Bohuslav Martinů|Symphony No. 4 (Martinů)",
"Dmitri Shostakovich|Symphony No. 9|1948|16MIEhqoHNI?start=60|Dmitri Shostakovich|Symphony No. 9 (Shostakovich)",
"Richard Strauss|Metamorphosen|1945|j4MDac_obuQ?start=60|Richard Strauss|Metamorphosen",
"Benjamin Britten|The Young Person’s Guide to the Orchestra|1945|4vbvhU22uAM|Benjamin Britten|The Young Person's Guide to the Orchestra",
"Igor Stravinsky|Symphony in Three Movements|1945|QyNA1k7yRbM?start=20|Igor Stravinsky|Symphony in Three Movements",
"Heitor Villa-Lobos|Bachianas Brasileiras No. 5|1945|pUCuEd1tjCg?start=20|Heitor Villa-Lobos|Bachianas Brasileiras",
"Aaron Copland|Symphony No. 3|1946|pfqCo_vuMsI|Aaron Copland|Symphony No. 3 (Copland)",
"Benjamin Britten|The Rape of Lucretia|1946-1947|440Pv6iSwcY|Benjamin Britten|The Rape of Lucretia",
"Arthur Honegger|Symphony No. 3, \"Symphonie liturgique\"|1946|jK9mGN7KZg4|Arthur Honegger|Symphony No. 3 \"Symphonie Liturgique\" (Honegger)",
"Xavier Montsalvatge|Canciones negras|1946|fCtnKLSVUlY|Xavier Montsalvatge|",
"Sergei Prokofiev|Violin Sonata No. 1|1946|LS0MlhTGxe8|Sergei Prokofiev|Violin Sonata No. 1 (Prokofiev)",
"Franz Waxman|Carmen Fantasie|1946|ZqYIdaZ0TwM|Franz Waxman|Carmen Fantasie (Waxman)",
"Kurt Weill|Street Scene|1946|xaCu-V3S7m8|Kurt Weill|Street Scene (opera)",
"Ned Rorem|Songs|1946-1999|OLAK5uy_lxeWsDkB8z1xuhHsdlAtp3ILQbBrIZWN0|Ned Rorem|",
"Arnold Schoenberg|A Survivor from Warsaw|1947|rGWai0SEpUQ|Arnold Schoenberg|A Survivor from Warsaw",
"Ralph Vaughan Williams|Symphony No. 6|1947-1950|yiFm7HVGkFo|Ralph Vaughan Williams|Symphony No. 5 (Vaughan Williams)",
"Maurice Durufle|Requiem|1947|Z1Wx87CtFPQ?start=68|Maurice Duruflé|Requiem (Duruflé)",
"Samuel Barber|Knoxville: Summer of 1915|1947|PQzaFJZ8CuE|Samuel Barber|Knoxville: Summer of 1915",
"Roberto Gerhard|The Duenna|1947|Fd5jzafBk5s|Robert Gerhard|The Duenna (opera)",
"John Cage|Sonatas and Interludes|1948|TJhv_k4xkMI|John Cage|",
"Aaron Copland|Clarinet Concerto|1948|9GnJBLwOjFo|Aaron Copland|Clarinet Concerto (Copland)",
"Conlon Nancarrow|Studies for Player Piano|1948-1993|PLC82C02554EEEB986|Conlon Nancarrow|Studies for Player Piano (Nancarrow)",
"Olivier Messiaen|Turangalîla Symphony|1948|eCO7le_6LzU?start=3|Olivier Messiaen|Turangalîla-Symphonie",
"Dmitri Shostakovich|From Jewish Folk Poetry|1948|Y-ajfgLVHaU|Dmitri Shostakovich|From Jewish Folk Poetry",
"Dmitri Shostakovich|Violin Concerto No. 1|1948|SXDk1CoIRuY|Dmitri Shostakovich|Violin Concerto No. 1 (Shostakovich)",
"Richard Strauss|Four Last Songs|1948|LIsdg-8PoRM?start=33|Richard Strauss|Four Last Songs",
"Leonard Bernstein|Symphony No. 2, \"The Age of Anxiety\"|1949-1965|Q-aU2Se1RHw|Leonard Bernstein|Symphony No. 2 (Bernstein)",
"Gerald Finzi|Clarinet Concerto|1949|GMukLZGaE0I|Gerald Finzi|",
"Gian Carlo Menotti|The Consul|1949|ekrx98zKnk0|Gian Carlo Menotti|The Consul",
"Sergei Prokofiev|Cello Sonata|1949|lWNiR1BuenY|Sergei Prokofiev|Cello Sonata (Prokofiev)",
"Astor Piazzolla|Tangos|1950-1952|57c70FU9-z0|Astor Piazzolla|",
"Malcolm Arnold|English Dances|1950-1951|YjWhe4njA5A|Malcolm Arnold|English Dances (Arnold)",
"Benjamin Britten|Billy Budd|1951-1960|A1lVBfqQyjs|Benjamin Britten|Billy Budd (opera)",
"Dmitri Shostakovich|Twenty-four Preludes and Fugues|1951|PLwGv0T3Az2lKdMri0D2M7mv1H0DwzxW6F|Dmitri Shostakovich|24 Preludes and Fugues (Shostakovich)",
"Francis Poulenc|Stabat Mater|1951|quemnTLY3fE|Francis Poulenc|Stabat Mater (Poulenc)",
"Igor Stravinsky|The Rake’s Progress|1951|DdJw86l22JA|Igor Stravinsky|The Rake's Progress",
"Sergei Prokofiev|Symphony-Concerto|1951|-rQyZYPvVew|Sergei Prokofiev|Symphony-Concerto (Prokofiev)",
"Heitor Villa-Lobos|Guitar Concerto|1951|A5M8EX88PGc|Heitor Villa-Lobos|Guitar Concerto (Villa-Lobos)",
"Sergei Prokofiev|Symphony No. 7|1952|mF8oTzXoyts|Sergei Prokofiev|Symphony No. 7 (Prokofiev)",
"Michael Tippett|The Midsummer Marriage|1952|XJbh2Alvw50|Michael Tippett|",
"Dmitri Shostakovich|Symphony No. 10|1953|gQU9hNxImxA|Dmitri Shostakovich|Symphony No. 5 (Shostakovich)",
"Michael Tippett|Corelli Fantasia|1953|Dts2_K_vG7A|Michael Tippett|Fantasia Concertante on a Theme of Corelli",
"Leonard Bernstein|Serenade|1954|Rp868n6rem8|Leonard Bernstein|Serenade after Plato's \"Symposium\"",
"Benjamin Britten|The Turn of the Screw|1954|PL6bLSbq1os-WIEgWEKY6VkouUtOyF7V78|Benjamin Britten|The Turn of the Screw (opera)",
"Aram Khachaturian|Spartacus|1954|LZLMKkEGFRo|Aram Khachaturian|Spartacus (ballet)",
"Witold Lutoslawski|Concerto for Orchestra|1954|7lwCIK7uENM?start=3|Witold Lutosławski|Concerto for Orchestra (Lutosławski)",
"Joaquin Rodrigo|Fantasia para un gentilhombre|1954|fnwV92IrClo|Joaquín Rodrigo|Fantasia",
"Iannis Xenakis|Metastaseis|1954|SZazYFchLRI|Iannis Xenakis|Metastaseis (Xenakis)",
"Alan Hovhaness|Symphony No. 2, \"Mysterious Mountain\"|1955|zQZBrJmzsrc|Alan Hovhaness|Symphony No. 2 (Hovhaness)",
"Pierre Boulez|Le marteau sans maître|1955|x2A30tJAH3s|Pierre Boulez|Le Marteau sans maître",
"Leonard Bernstein|Candide|1956-1989|422-yb8TXj8|Leonard Bernstein|Candide (operetta)",
"William Walton|Cello Concerto|1956-1975|FVO_CevHNnM|William Walton|Cello Concerto (Walton)",
"Malcolm Williamson|Piano Works|1956-1984|se5HsLCZRo8|Malcolm Williamson|",
"Francis Poulenc|Dialogues des Carmélites|1956|Cd9EFJaURmI|Francis Poulenc|Dialogues of the Carmelites",
"Leonard Bernstein|West Side Story|1957|srb2EyvTSGw|Leonard Bernstein|America (West Side Story song)",
"Dmitri Shostakovich|Piano Concerto No. 2|1957|HLlxUFlv1mo?start=15|Dmitri Shostakovich|Piano Concerto No. 2 (Shostakovich)",
"Samuel Barber|Vanessa|1957-1964|oLVWMRwSCxg|Samuel Barber|Vanessa (opera)",
"Karlheinz Stockhausen|Gruppen|1957|34_SfP7ZCXA|Karlheinz Stockhausen|",
"Igor Stravinsky|Agon|1957|Ud8zVcHPnuM|Igor Stravinsky|Agon (ballet)",
"Dmitri Shostakovich|Symphony No. 11, \"The Year 1905\"|1957|RGyQkm0fFnY|Dmitri Shostakovich|Symphony No. 11 (Shostakovich)",
"Michael Tippett|Symphony No. 2|1957|EPHCTbd5a_Y|Michael Tippett|Symphony No. 2 (Tippett)",
"Olivier Messiaen|Catalogue d’oiseaux|1958|G6Izpdkjrhk|Olivier Messiaen|Catalogue d'oiseaux",
"Luciano Berio|Sequenzas|1958-2002|P7myJxdhf9Y?start=14|Luciano Berio|Sequenza",
"Hanns Eisler|Deutsche Sinfonie|1959|jgW_F3hT34Q|Hanns Eisler|",
"Francis Poulenc|La voix humaine|1959|M2V85r8S_B4|Francis Poulenc|La voix humaine",
"Dmitri Shostakovich|Cello Concerto No. 1|1959|h23WjKXDe4w|Dmitri Shostakovich|Cello Concerto No. 1 (Shostakovich)",
"Benjamin Britten|A Midsummer Night’s Dream|1960|PLG4v5n-7yNWtZxivGu8kvxnuOs_EvOwsW|Benjamin Britten|A Midsummer Night's Dream (opera)",
"Dmitri Shostakovich|String Quartet No. 8|1960|lFHmQQ6NqbY?start=485|Dmitri Shostakovich|String Quartet No. 8 (Shostakovich)",
"Krzysztof Penderecki|Threnody to the Victims of Hiroshima|1960|Pu371CDZ0ws|Krzysztof Penderecki|Threnody to the Victims of Hiroshima",
"Karlheinz Stockhausen|Kontakte|1960|o7JFAAgwMWo|Karlheinz Stockhausen|Kontakte",
"Bernd Alois Zimmermann|Die Soldaten|1960-1964|dTXLxNIEcJ0|Bernd Alois Zimmermann|Die Soldaten",
"Elliott Carter|Double Concerto|1961|sebIvdCHcCE|Elliott Carter|Double Concerto (Carter)",
"Benjamin Britten|War Requiem|1962|rsSMCq7pl_k|Benjamin Britten|War Requiem",
"Gyorgy Ligeti|Aventures & Nouvelles aventures|1962-1966|x6xtllQsmMU|György Ligeti|",
"Dmitri Shostakovich|Symphony No. 13, \"Babi Yar\"|1962|acDDPoopgvw|Dmitri Shostakovich|Symphony No. 13 (Shostakovich)",
"Olivier Messiaen|Et exspecto resurrectionem mortuorum|1964|3f4qdJHatNM|Olivier Messiaen|",
"Giacinto Scelsi|String Quartet No. 4|1964|QSHSBwUqP-Y|Giacinto Scelsi|",
"Benjamin Britten|Curlew River|1964|UElSN7HTSeM|Benjamin Britten|Curlew River",
"Peter Maxwell Davies|Second Fantasia on John Taverner’s In Nomine|1964|0sg82OAgB2g|Peter Maxwell Davies|",
"Henri Dutilleux|Métaboles|1964|u2vgcxvb1K0|Henri Dutilleux|Métaboles",
"Dmitri Shostakovich|String Quartet No. 10|1964|syJy_0KNAOQ|Dmitri Shostakovich|String Quartet No. 10 (Shostakovich)",
"Leonard Bernstein|Chichester Psalms|1965|7Yhnml4DW9g|Leonard Bernstein|Chichester Psalms",
"Rodion Shchedrin|Carmen Suite|1967|QysD8zCfGTs|Rodion Shchedrin|Carmen Suite (ballet)",
"Dmitri Shostakovich|Seven Romances on Poems by Alexander Blok|1967|2K-DtBpDwuY?start=330|Dmitri Shostakovich|Seven Romances on Poems by Alexander Blok",
"Gyorgy Ligeti|String Quartet No. 2|1968|rMd6EEqukWo|György Ligeti|",
"Dmitri Shostakovich|Violin Sonata|1968|GFUAZ8cKMD4?start=10|Dmitri Shostakovich|Violin Sonata (Shostakovich)",
"Karlheinz Stockhausen|Stimmung|1968|OLAK5uy_mnYfVRiw0SkRJC5wQORBIK1GqShigxNVY|Karlheinz Stockhausen|Stimmung",
"Luciano Berio|Sinfonia|1969|V1XSmiGO3XE|Luciano Berio|Sinfonia (Berio)",
"Dmitri Shostakovich|Symphony No. 14|1969|bAzZcKB6LO8?start=42|Dmitri Shostakovich|Symphony No. 14 (Shostakovich)",
"Elliott Carter|Concerto for Orchestra|1969|eV0bLIMUvWs|Elliott Carter|Concerto for Orchestra",
"Peter Maxwell Davies|Eight Songs for a Mad King|1969|KgCstNqsu8Y|Peter Maxwell Davies|Eight Songs for a Mad King",
"Henri Dutilleux|Tout un monde lointain…|1970|O2qmECLxnCY|Henri Dutilleux|Tout un monde lointain...",
"Elliott Carter|String Quartet No. 3|1971|6njANe60Evw|Elliott Carter|String Quartet No. 3 (Carter)",
"Dmitri Shostakovich|Symphony No. 15|1971|N0iZGMXpquQ|Dmitri Shostakovich|Symphony No. 15 (Shostakovich)",
"Morton Feldman|Cello and Orchestra|1972|UY-Nsz9XSe8|Morton Feldman|",
"Harrison Birtwistle|The Triumph of Time|1972|uDoEjFZsSA4|Harrison Birtwistle|The Triumph of Time (Birtwistle)",
"Bruno Maderna|Aura|1972|iqXLRB4Ooho|Bruno Maderna|",
"Einojuhani Rautavaara|Cantus arcticus|1972|8X2FU1KU4_U|Einojuhani Rautavaara|Cantus Arcticus",
"Benjamin Britten|Death in Venice|1973|bIm4jDmnKMQ|Benjamin Britten|Death in Venice",
"Dmitri Shostakovich|String Quartet No. 15|1974|QccUkIhrrO8|Dmitri Shostakovich|String Quartet No. 15 (Shostakovich)",
"Pierre Boulez|Rituel in memoriam Bruno Maderna|1975|3WuwS94WDRQ|Pierre Boulez|Rituel in memoriam Bruno Maderna",
"Steve Reich|Music for 18 Musicians|1976|ZXJWO2FQ16c?start=33|Steve Reich|Music for 18 Musicians",
"Philip Glass|Einstein on the Beach|1976|OLAK5uy_lIB1Za0mJ0vRmIbL6gv9IonJ2fawvmEKI|Philip Glass|Einstein on the Beach",
"Henryk Górecki|Symphony No. 3|1976|DoaEEVMrL-g?start=43|Henryk Górecki|Symphony No. 3 (Górecki)",
"Gyorgy Ligeti|Le Grand Macabre|1977-1996|68cBI89ByjM?start=85|György Ligeti|Le Grand Macabre",
"John Corigliano|Clarinet Concerto|1977|m72j7Vjv3WM|John Corigliano|Clarinet Concerto (Corigliano)",
"Toru Takemitsu|A Flock Descends into the Pentagonal Garden|1977|3--e-iOiGDM|Tōru Takemitsu|",
"Arvo Pärt|Fratres|1977|7vdgZAJVnes|Arvo Pärt|",
"Einojuhani Rautavaara|Angels and Visitations|1978|autfEuxRICI|Einojuhani Rautavaara|",
"Pierre Boulez|Notations|1978|uIlfuf2wUok?start=3|Pierre Boulez|",
"Michael Tippett|String Quartet No. 4|1978|-7AV0WJdfdg|Michael Tippett|",
"John Cage|Roaratorio|1979|bdHe4c10smY|John Cage|Roaratorio",
"George Benjamin|Ringed by the Flat Horizon|1980|1x3a5aei12Q|George Benjamin (composer)|",
"Sofia Gubaidulina|Offertorium|1980|xvHeTWOfL1c|Sofia Gubaidulina|Offertorium",
"Brian Ferneyhough|Funérailles|1980|mzTmjDmyx4k|Brian Ferneyhough|",
"Tristan Murail|Gondwana|1980|q6WXzOIsBuQ|Tristan Murail|Gondwana (Murail)",
"Jonathan Harvey|Mortuos Plango, Vivos Voco|1980|0T-H-fVlHE0|Jonathan Harvey|Mortuos Plango, Vivos Voco",
"William Bolcom|Songs of Innocence and Experience|1981|OLAK5uy_kkDXO-7p-NaSEjbADCFu9yYlbIZiSLeTI|William Bolcom|https://en.wikipedia.org/wiki/Songs_of_Innocence_and_of_Experience#Musical_settings",
"John Tavener|Funeral Ikos|1981|4ZRrbixpVV0|John Tavener|",
"Olivier Messiaen|Saint François d’Assise|1983|0TufQgNdfss|Olivier Messiaen|Saint François d'Assise",
"Oliver Knussen|Where the Wild Things Are|1984|PLSO9Kihiwr3N56_74IUqZT-2QG1-dM503|Oliver Knussen|Where the Wild Things Are (opera)",
"Olivier Messiaen|Livre du Saint Sacrement|1984|OLAK5uy_m-j_MmnHsznUO-fUr1In7oPfhE4xuqT6Q|Olivier Messiaen|",
"Hans Werner Henze|Symphony No. 7|1984|QmRpoA74BME|Hans Werner Henze|",
"Helmut Lachenmann|Mouvement (-vor der Erstarrung)|1984|zRLBdHR2L7c|Helmut Lachenmann|Mouvement (– vor der Erstarrung)",
"John Adams|Harmonielehre|1985|a74Cg0jdR0c|John Adams (composer)|Harmonielehre",
"Gyorgy Ligeti|Études|1985-2004|XHhZ2TzHlow|György Ligeti|Études (Ligeti)",
"Witold Lutoslawski|Chain 2|1985|BeO4tKt3Ekg|Witold Lutosławski|",
"Alfred Schnittke|String Trio|1985|kueXf27ecz8|Alfred Schnittke|",
"Milton Babbitt|Transfigured Notes|1986|o4ovTeWNPV4|Milton Babbitt|",
"Peter Sculthorpe|Earth Cry|1986|FWuLo3wyWFQ|Peter Sculthorpe|",
"Philip Glass|Violin Concerto|1987|5lGNtPXcA04|Philip Glass|Violin Concerto No. 1 (Glass)",
"John Adams|Nixon in China|1987|G72JjpMEdKs|John Adams (composer)|Nixon in China",
"John Tavener|The Protecting Veil|1987|xT0MF4XNjkA|John Tavener|The Protecting Veil",
"Louis Andriessen|De Materie|1988|OLAK5uy_nNB6P-Q3PRGxAlesE6MVMuv0s-JJmc6D8|Louis Andriessen|De Materie",
"Ross Edwards|Maninyas|1988|Kip8rQX0_BY|Ross Edwards (composer)|",
"Steve Reich|Different Trains|1988|qcGqVynCPaw|Steve Reich|",
"Mark-Anthony Turnage|Three Screaming Popes|1989|eiGo37janfU|Mark-Anthony Turnage|",
"Gyorgy Kurtag|Officium breve|1989|D4CdOOWvtWk|György Kurtág|",
"James MacMillan|Veni, veni, Emmanuel|1992|W5M9nfC6apM|James MacMillan|Veni, Veni, Emmanuel (MacMillan)",
"Olivier Messiaen|Éclairs sur l’Au-delà…|1992|EA53UMx7dHY|Olivier Messiaen|Éclairs sur l'Au-Delà...",
"Simon Bainbridge|Ad ora incerta|1994|OLAK5uy_mxoeSq1DWUAAELGXIBdGLIy-ok06bdALg|Simon Bainbridge|",
"Gyorgy Kurtag|Stele|1994|WiqCwQ8nJhY|György Kurtág|Stele (Kurtág)",
"Magnus Lindberg|Aura|1994|E_fqQSiD4vA|Magnus Lindberg|Aura (Magnus Lindberg)",
"Carl Vine|Percussion Symphony|1995|3BVcPl3_nj0|Carl Vine|",
"Mark-Anthony Turnage|Blood on the Floor|1996|PLwV26up9YlHT3uq3srR5ieyBWm-_69jke|Mark-Anthony Turnage|Blood on the Floor (Turnage)",
"Thomas Adès|Asyla|1997|Tb8LWa3eak8|Thomas Adès|Asyla",
"Sofia Gubaidulina|Canticle of the Sun|1997|j5r2vvQI_Ck|Sofia Gubaidulina|The Canticle of the Sun (Gubaidulina)",
"Peteris Vasks|Violin Concerto, \"Distant Light\"|1997|xtdFecPt92M?start=50|Pēteris Vasks|",
"Gerard Grisey|Quatre chants pour franchir le seuil|1998|06MnaNz_CgQ|Gérard Grisey|",
"Wolfgang Rihm|Deus Passus|2000|OLAK5uy_kXyji22DQmH4_b593CV40YHOUc5DwMMHM|Wolfgang Rihm|",
"Wolfgang Rihm|Jagden und Formen|2001|82shObbF31M|Wolfgang Rihm|",
"Julian Anderson|Book of Hours|2004|nSWuED4bZLU|Julian Anderson|",
] 
